"""Reading verdicts a fresh install starts with - see
discover._load_reading_meta. Generated 6 September 2026 from one
machine's reading_meta.json: lowercased title -> the medium MangaDex
files it under, and the genre tags of a title that matched at 0.85.
Data, not code; regenerate rather than edit."""

MEDIUM = {
    '+99 wooden stick': 'Manhwa',
    '1/24 romance': 'Manhwa',
    '100 million years later: the ultimate weapon’s return': 'Other',
    "18-year-old villainess' target": 'Manhwa',
    '2072267132 call of the spear': 'Other',
    '2072267132 doomsday for all me virus monarch': 'Other',
    '2072267132 i picked a hammer to save the world': 'Manhwa',
    '2072267132 im really not the devils lackey': 'Other',
    '2072267132 logging 10 000 years into the future': 'Other',
    '2072267132 necromancer academys genius summoner': 'Manhwa',
    '2072267132 start by signing in and obtaining the ancient divine body': 'Manhua',
    '2072267132 super god pet beast shop': 'Other',
    '2072267132 the eternal supreme': 'Other',
    '30 years since the prologue': 'Manhwa',
    '404 case manual: 30 seconds till apocalypse': 'Manhua',
    'a baby dragon saves the dukedom': 'Manhwa',
    'a barbarian’s adventure in a fantasy world': 'Manhwa',
    'a blank slate regression for the idol that lost his original mindset': 'Manhwa',
    'a butchers cleaver can topple the myriad realms right': 'Other',
    'a cadet becomes a prophet': 'Manhwa',
    'a corporate underling who excels at work': 'Manhwa',
    "a dragonslayer's peerless regression": 'Manhwa',
    'a dragonslayers peerless regression': 'Manhwa',
    'a fortune-telling princess': 'Manhwa',
    'a glimpse of the jianghu': 'Manhua',
    'a love that crosses the line': 'Manhwa',
    'a mercenary’s rebirth among nobles': 'Manhwa',
    'a modern man who got transmigrated into the murim world': 'Manhwa',
    'a painter who draws dungeons': 'Manhwa',
    'a saint who was adopted by the grand duke': 'Manhwa',
    'a sister must raise her younger sister properly': 'Manhwa',
    'a spys survival in the demonic cult': 'Manhwa',
    'a strange life': 'Manhwa',
    'a wimps strategy guide to conquer the tower': 'Manhwa',
    'a wimp’s strategy guide to conquer the tower': 'Manhwa',
    'absolute domination at level 0 using my analysis skill': 'Other',
    'absolute scholar': 'Manhwa',
    'absolute sword sense': 'Manhwa',
    "academy's genius swordmaster": 'Manhwa',
    'after million of years i woke up to be a god': 'Manhua',
    'after rebirth, i used mirror reversal for vengeance': 'Other',
    'after the possessor left1': 'Manhwa',
    'against the gods': 'Manhua',
    'ags': 'Other',
    'algd almharb oalhfyd alaalya': 'Other',
    'all hail the sect leader': 'Manhua',
    'all my alter egos are tycoons': 'Manhwa',
    'all people scramble for the tower: i cleared 999 floors in advance': 'Manhua',
    'all rounder': 'Manhwa',
    'altragaa bko almlk': 'Other',
    'an art student who lives twice': 'Manhwa',
    'an extra who wants to escape the obsessive male lead': 'Manhwa',
    'an unparalleled martial arts spirit': 'Other',
    'ancient teacher': 'Other',
    'ankle breaker': 'Manhwa',
    'annihilation of the heavenly way': 'Other',
    'apocalypse mechanic': 'Manhua',
    'apocalypse sword god i shock the world': 'Other',
    'apocalyptic chef awakening': 'Manhwa',
    'apocalyptic heat i became a god using my safe house': 'Other',
    'apotheosis': 'Manhua',
    'archmage curriculum': 'Manhwa',
    'archmage transcending through regression': 'Manhwa',
    'aristocrats revenge': 'Manga',
    'artifact reading appraiser': 'Manhwa',
    'artifact-devouring player': 'Manhwa',
    "askr yggdrasil's wood": 'Manhua',
    'at the abyss of fall i find you': 'Other',
    'at the abyss of fall, i find you': 'Other',
    'auto hunting with my clones': 'Manhwa',
    'awakening the purple thunder at the beginning': 'Manhua',
    'baby prisoner of the winter castle': 'Manhwa',
    'baby squirrel is good at everything': 'Manhwa',
    'back to rule again': 'Manhua',
    'back to the city: the strongest investment king': 'Other',
    'baki rahen': 'Manga',
    'bate': 'Other',
    'became a medieval fantasy wizard': 'Manhwa',
    'becoming a legendary ace employee': 'Manhwa',
    'becoming an immortal official starts with transmigrating as a hog': 'Other',
    "becoming the cheon clan's mad dog": 'Other',
    'begin': 'Manga',
    'behind the laughter of the surviving princess': 'Manhwa',
    'berserk': 'Manga',
    'black corporation: joseon': 'Manhwa',
    'black killer whale baby': 'Manhwa',
    'black man ill do everything for you except marriage': 'Other',
    'blade debt': 'Manhua',
    'blades of the guardians': 'Manhua',
    'blocking monsters with monsters': 'Other',
    'blood breakrr': 'Other',
    'blood system': 'Manhua',
    'bones': 'Manhwa',
    'boss beating': 'Other',
    'boundless necromancer': 'Manhwa',
    'bungou stray dogs: dazai wo hirotta hi': 'Manga',
    'call of the spear': 'Manhwa',
    'capital’s most crazy doctor': 'Manhua',
    'carrying the goddess along': 'Manhua',
    'castle': 'Manhwa',
    'cataclysm hunter: i have an experience points system': 'Manhua',
    'catastrophic necromancer': 'Manhua',
    'celebrity lady': 'Manhwa',
    'ceres the time healer': 'Other',
    'ceres, the time healer': 'Other',
    'charlotte has five disciples': 'Manhwa',
    'chat with me': 'Manhwa',
    'childhood friend of the zenith': 'Manhwa',
    'children of the rune': 'Manhwa',
    'chronicle of runes': 'Manhwa',
    'chronicles of the absolute song sect': 'Other',
    'chronicles of the demon faction': 'Manhwa',
    'chronicles of the lazy sovereign': 'Manhwa',
    'chronicles of the moonlit night': 'Other',
    'chrono labyrinth': 'Manga',
    'classmates': 'Manga',
    'cm': 'Manhwa',
    'coffe thief': 'Manhwa',
    'concept grasping magic genius': 'Manhwa',
    'cosmic heavenly demon 3077': 'Manhwa',
    'crimson reset': 'Manhwa',
    'cultivator against hero society': 'Manhua',
    'damn demonic swords': 'Manhwa',
    'damn reincarnation': 'Manhwa',
    'dare i hope': 'Manhwa',
    'dark and light martial emperor': 'Manhwa',
    'dch': 'Other',
    'dearest fiance i know you despise me': 'Manhwa',
    'death is the only ending for the villainess': 'Manhwa',
    'defiance of the fall': 'Other',
    'demon god reincarnation': 'Manhwa',
    'demonic emperor': 'Manhua',
    'detective conan': 'Manga',
    'devil summoner i am the abyss lord': 'Manhua',
    'disaster comes i evolve in to the crimson king': 'Other',
    'divine spirit': 'Manhua',
    'dog eat dog': 'Manga',
    'doom summoner': 'Manhua',
    'doomsday arrival: evolution into the crimson king': 'Manhua',
    'doomsday for all me virus monarch': 'Other',
    'dr. hound': 'Manhwa',
    'dragon-devouring mage': 'Manhwa',
    'dream cycle reincarnation: i became the supreme martial king': 'Other',
    'duke pendragon': 'Manhwa',
    'dukedom’s legendary prodigy': 'Manhwa',
    'dumped by my girlfriend so i turned to martial arts': 'Manhua',
    'dungeon athlete': 'Manhwa',
    'dungeon defense': 'Manga',
    'dusk divide': 'Other',
    'ebony': 'Manhwa',
    'ebony 3': 'Other',
    'ecd': 'Other',
    'egflbroj': 'Other',
    'emperor and the female knight': 'Manhwa',
    'emperor of solo play': 'Manhwa',
    'en travesti – i became a fake prince': 'Manhwa',
    'enigmatica': 'Manga',
    'entomologist in sichuan tang clan': 'Manhwa',
    'eternal kingdom': 'Manhua',
    'even madness strikes thrice': 'Manhwa',
    'everlasting longing': 'Other',
    'everyone was obsessed with me after i became the youngest princess favourite': 'Manhwa',
    'everything was a mistake': 'Manhwa',
    'evolution begins with a big tree': 'Manhua',
    'executioner': 'Manga',
    'extracted into the god of necromancy': 'Manhua',
    'f-class destiny hunter': 'Manhwa',
    'fantasy induction corps': 'Other',
    'fated to be loved by villains': 'Manhwa',
    'father, i don’t want to get married!': 'Manhwa',
    'feasting lord in another world': 'Manhwa',
    'fechippuru ~our innocent love.': 'Manga',
    'festival of warriors': 'Manhwa',
    'fff-class trashero': 'Manhwa',
    'for my gentle monster': 'Other',
    'free in dreams': 'Manhwa',
    'from child actor to global superstar!': 'Other',
    'from disgraced lady to beloved stepmother': 'Other',
    'frozen frontiers': 'Manhua',
    'full time awakening': 'Manhua',
    'full time hunter i hunt the world': 'Manhua',
    'full-time awakening': 'Manhua',
    'full-time hunter: i hunt the world!': 'Manhua',
    'game obu familia - family senki': 'Manga',
    'gangnam sink': 'Manhwa',
    'gatekeeper of the boundless world': 'Manhua',
    'genius archer’s streaming': 'Manhwa',
    'genius martial arts trainer': 'Other',
    'ghosting groom': 'Manhwa',
    'gizmo riser': 'Other',
    'glass wall': 'Manhwa',
    'global beast tamer i can see the path of evolution': 'Manhua',
    'global class awakening the mage kings skills gain infinite upgrades': 'Other',
    'global game i can have 100 fold amplification': 'Other',
    'global job change starting with the hidden class necromancer lord': 'Manhua',
    'global job change: starting with the hidden class necromancer lord': 'Manhua',
    'glory': 'Other',
    'go deok chuns food truck': 'Manhwa',
    'goblin corporation': 'Manga',
    'goblin inc': 'Manhwa',
    'god of martial arts': 'Manhua',
    'golden mage': 'Manhwa',
    'golden martial god': 'Manhwa',
    'goodbye ex husband': 'Other',
    'goodbye, ex-husband': 'Other',
    'got dropped into a ghost story': 'Manhwa',
    'got dropped into a ghost story, still gotta work': 'Manhwa',
    'got dropped into a horror story, still gotta work': 'Manhwa',
    'grand general': 'Manhwa',
    'greatest boss system': 'Manhua',
    'green skin': 'Manhwa',
    'greet the sect leader': 'Other',
    'guard pass': 'Manhwa',
    'haikyuu oneshot': 'Other',
    'happy face from slave to arena legend': 'Manhwa',
    "harvest governor's envoy": 'Other',
    'hataraku maou sama': 'Manga',
    'hazure skill "kage ga usui" o motsu guild shokuin ga, jitsuha densetsu no ansatsusha': 'Manga',
    'healing at the academy convenience store': 'Manhwa',
    'healing life through camping in another world': 'Manhwa',
    'heavenly demon cultivation simulation': 'Manhwa',
    'heavenly demon tavern': 'Manhwa',
    'heavenly demon wants to be a chef': 'Manhwa',
    'heavenly grand archive’s young master': 'Manhwa',
    'heavenly inquisition sword': 'Manhwa',
    'heavenly martial god': 'Manhwa',
    'heir of mythical heroes': 'Manhwa',
    'hello griffin the fluffy bird': 'Manhwa',
    'hello mr. veterinarian!': 'Manhwa',
    'hellogin': 'Other',
    'hero of all trades': 'Manhwa',
    'heroes of the imjin war': 'Manhwa',
    'high martial world with one hand he sweeps aside three thousand emperors': 'Other',
    'high society': 'Manhwa',
    'high-martial world: with one hand he sweeps aside three thousand emperors!': 'Other',
    'horror rpg maker survival story': 'Manhwa',
    'how i became a married man in another world': 'Manhwa',
    'how the sword emperor establishes the namgung clan': 'Other',
    'how to fight': 'Manhwa',
    'how to live as a civil servant in murim': 'Manhwa',
    'how to live as an unlicensed healer': 'Other',
    'how to save a time limited young master': 'Manhwa',
    'how to survive as the daughter of the emperor who killed me': 'Manhwa',
    'how to survive as the devils daughter': 'Manhwa',
    'how to turn you around': 'Manhwa',
    'hunter academys battle god': 'Manhwa',
    "hunter world's gardener": 'Manhwa',
    'hunter x hunter': 'Manga',
    'hunter x hunter colored': 'Manga',
    "i am in a secret relationship with the emperor, but i don't know it": 'Other',
    'i am the fated villain': 'Manhua',
    'i awoke as a god after auto battling for a million years': 'Manhua',
    'i became a genius in sales': 'Manhwa',
    'i became a victim of the king of the wolves': 'Other',
    'i became the daughter of a million-dollar actor': 'Other',
    'i became the genius bastard of a noble dark clan': 'Manhwa',
    'i became the king by scavenging': 'Manhua',
    'i became the leader of a cursed idol groupe': 'Other',
    'i became the master of the weakest demon king': 'Manhwa',
    'i became the rogue first prince': 'Manhwa',
    'i became the successor of the martial god': 'Manhwa',
    'i became the tyrant of a defense game': 'Manhwa',
    "i became the tyrant's time limited wife": 'Manhwa',
    'i became the tyrants servant': 'Manhwa',
    'i became the tyrant’s servant': 'Manhwa',
    'i became the tyrant’s time-limited wife': 'Manhwa',
    'i became the wife of the male lead': 'Manhwa',
    'i became the youngest prince in the novel': 'Manhwa',
    'i became the youngest sister in law of the male leads ruined harem': 'Manhwa',
    'i become a hatchling': 'Other',
    'i become a legendary arch mage by reading a book': 'Other',
    'i become the youngest disciple of the martial arts leader': 'Manhwa',
    'i can snatch 999 types of abilities read': 'Manhua',
    'i contracted myself': 'Manhua',
    'i dont want to be a magip bridge': 'Manhwa',
    'i ended up raising my younger self': 'Other',
    'i gave up being stronger': 'Manhwa',
    'i have a shanzhai': 'Manhua',
    'i have an sss-rank trait, but i want a normal life': 'Manhwa',
    'i have six months to live, but i’ve captivated the tyrant emperor': 'Other',
    'i kidnapped the youngest daughter of the sichuan tang clan': 'Manhwa',
    'i long for your despair': 'Other',
    'i married the dragon i killed': 'Manhwa',
    "i only need the duke's child": 'Manhwa',
    'i opened the era of mythical beasts': 'Other',
    'i picked a hammer to save the world': 'Manhwa',
    'i really dont want to learn forbidden spells': 'Manhua',
    'i received a request from the villain boss': 'Manhwa',
    'i regressed to my ruined family': 'Manhwa',
    'i reincarnated as a legendary surgeon': 'Manhwa',
    'i reincarnated as a villainess but why did i become a cat butler instead': 'Manhwa',
    'i reincarnated as a villainess, but why did i become a cat butler instead?': 'Manhwa',
    'i reincarnated as the crazed heir': 'Manhwa',
    'i reincarnated as the daughter of a runaway sub heroine': 'Other',
    "i saved you, but i'm not responsible": 'Manhwa',
    'i shall seal the heavens 2025': 'Manhua',
    "i tamed my ex-husband's mad dog": 'Manhwa',
    'i told you to farm but you became an emperor': 'Manhua',
    'i took over the system players': 'Manhua',
    'i was immediately mistaken for a monster genius actor': 'Manhwa',
    'i was stuck on the same day for 3,000 years': 'Manhua',
    'i was thrown into an unknown manga': 'Manhwa',
    'i was trash': 'Manhua',
    'i watched a play': 'Other',
    'i will raise this family to greatness': 'Manhwa',
    'i will try to raise the villain properly': 'Other',
    "i'm a beginner, but i'm actually the strongest level 99 player": 'Other',
    "i'm a former office worker reborn as the villainess of the apocalypse": 'Other',
    "i'm a sickly mother but i'll raise my villainous son!": 'Manga',
    "i'm a young system won't you raise m": 'Other',
    "i'm a young system, won't you raise me?": 'Other',
    "i'm being chased by my husband": 'Manhwa',
    "i'm looking for a new husband": 'Manhwa',
    "i'm the youngest disciple of the murim's mastermind": 'Other',
    "i'm trying to become part of the dark duke's family": 'Other',
    'if ai rules the world': 'Manhwa',
    'ill retire after saving the world': 'Manhwa',
    'im a beginner but im actually the strongest level 99 player': 'Other',
    'im a homebody but i possessed a depraved confinement novel': 'Other',
    'im a villainess but im favored': 'Other',
    'im being chased by my husband': 'Manhwa',
    'im going to destroy this country': 'Manhwa',
    'im gonna annihilate this land': 'Manhwa',
    'im looking for a new husband': 'Manhwa',
    'im really not the devils lackey': 'Manhua',
    'im the tyrant familys beloved baby': 'Other',
    'immortal swordsman in the reverse world': 'Manhua',
    'immortals way of life': 'Manhwa',
    'imperfect sister': 'Manhwa',
    'in': 'Manga',
    'in the shadow of the spring': 'Manhwa',
    'in this life, i will be the lord': 'Manhwa',
    'infinite breakthrough': 'Manga',
    'infinite level up in murim': 'Manhwa',
    'infinite mage': 'Manhwa',
    'insanely-talented player': 'Manhwa',
    'interspecies protection agency': 'Manhwa',
    'invasion of the myriad races starting by taming a legendary beast': 'Manhua',
    'inverse scale': 'Manhua',
    "is it bad that the main character's a roleplayer": 'Manhwa',
    'is it bad that the main character’s a roleplayer': 'Manhwa',
    'isnt being a wicked woman much better': 'Manhwa',
    'isnt this inside the game': 'Manhwa',
    'it all starts with playing game seriously': 'Manhua',
    'its jiyujiyo': 'Other',
    'i’ll be taking a break for personal reasons': 'Manhwa',
    'i’m going to destroy this country': 'Manhwa',
    'i’m not that kind of talent': 'Manhwa',
    'i’m really not a demon lord': 'Manhua',
    'i’m trying to become part of the dark duke’s family': 'Other',
    'i’m using the hero to servive!': 'Other',
    'jackpot after divorce': 'Manhwa',
    'judgment': 'Manhwa',
    'jungle juice': 'Manhwa',
    'kaijuno8': 'Other',
    'kaiten no albus': 'Manga',
    'kamisama ni kago 2 nin bun moraimashita': 'Manga',
    'kengan ashura': 'Manga',
    'kengan omega': 'Manga',
    'kidnapped by the earth': 'Manhua',
    'kidnapped dragons': 'Other',
    'kill the dragon': 'Manhwa',
    'killer pietro': 'Manhwa',
    'killing guard': 'Manga',
    'king of the cartel': 'Manhwa',
    'kingdom': 'Manga',
    'kingdom (wan)': 'Manga',
    'kingdom hearts': 'Manga',
    'kot': 'Other',
    'kouryakuhon o kushi suru saikyou no mahoutsukai ~ to wa iwa senai oreryuu mao tobatsu saizen ruuto ~': 'Manga',
    'kuma gurashi': 'Manga',
    'la ykhr fy alshrk': 'Other',
    "lee seop's love": 'Manhwa',
    'lee seops love': 'Manhwa',
    'legend of sho': 'Manhua',
    'legend of star general': 'Manhua',
    'legend of the northern blade': 'Manhwa',
    'legend of the reincarnated demon god': 'Manhwa',
    'lemon tree grove': 'Other',
    'let me play in peace': 'Manhua',
    'level drain': 'Manga',
    'level up with skills': 'Manhwa',
    'leveling up my lifes luck': 'Manhwa',
    'leveling up with gods': 'Manhwa',
    'leveling up, by only eating!': 'Manhwa',
    'leviathan table': 'Manga',
    'life of a magic academy mage': 'Manhwa',
    'life of a war emperor after retirement': 'Manhua',
    'life or death for an unrequited love': 'Manhwa',
    'light of the dawn remake': 'Manhwa',
    'lightning degree': 'Manhwa',
    'like a chilling flame': 'Manhwa',
    'lingering pain': 'Manhwa',
    'live with me': 'Manhwa',
    'living with an aberrant lifeform in my body': 'Manhua',
    'logging 10 000 years into the future': 'Other',
    'logging 10.000 years into the future': 'Manhua',
    'looking for a top-tier fighting coach': 'Manhwa',
    'looking for the strongest': 'Other',
    'looking for the villainess’s contract husband': 'Manhwa',
    'lookism': 'Manhwa',
    "lord preston's secret tutor": 'Manhwa',
    'lord preston’s secret tutor': 'Manhwa',
    'loyal heart roaming the skies': 'Other',
    'lsk': 'Manhua',
    "lu bu's life simulator": 'Manhua',
    'lu bus life simulator': 'Manhua',
    'magic academy’s genius blinker': 'Manhwa',
    'magic level 99990000 all-attribute great sage': 'Manga',
    'manager kim': 'Manhwa',
    'margraves worthless son': 'Other',
    "marked as the tyrant's daughter in law": 'Manhwa',
    'marquis maron': 'Other',
    'marriage defense scandal': 'Other',
    'marriage of convenience 2: an unforgettable song': 'Manhwa',
    'martial arts alone': 'Manhwa',
    'martial arts of demonic humans': 'Manhua',
    'martial peak': 'Manhua',
    'max level player': 'Manhwa',
    'maxed out leveling': 'Manhwa',
    'maxed strength necromancer': 'Manhua',
    'me and my brother': 'Other',
    'medical martial arts': 'Manhua',
    'memoir of the king of war': 'Manhwa',
    'mercenary enrollment': 'Manhwa',
    'metropolitan reverence': 'Manhua',
    'mharaty alkamn la tkhr': 'Other',
    'miracle app store\u200f': 'Manhwa',
    'monopolizing fortunes': 'Other',
    'monster pet evolution': 'Manhua',
    'mookhyang - dark lady': 'Manhwa',
    'moon-shadow sword emperor': 'Manhwa',
    'mortal cultivation: biography': 'Manhua',
    'mortals cultivation journey to immortality': 'Manhua',
    'mount hua sects genius phantom swordsman': 'Other',
    'mountain of corpses and sea of blood': 'Manhua',
    'mr devourer please act like a final boss': 'Manhwa',
    'murim login': 'Manhwa',
    'murim psychopath': 'Manhwa',
    'mushoku tensei - isekai ittara honki dasu': 'Manga',
    'my basic attacks summon the undead i the dark ranger am the true calamity': 'Manhua',
    'my clone is the space bug king': 'Manhua',
    'my dad is the strongest under heaven': 'Other',
    'my daddy hides his power': 'Manhwa',
    'my daughter is the final boss': 'Manhwa',
    'my dream is to get my own house': 'Other',
    'my guild is full of demons': 'Manhua',
    'my healing skill can copy anything so i conquered the abyss': 'Manhua',
    'my house is a magic power spot': 'Manga',
    'my husband possessed the protagonist': 'Other',
    'my inventory is abnormal': 'Manhwa',
    'my life as a loser': 'Manhwa',
    'my pirate prince': 'Manhwa',
    'my plug-in spirit ring': 'Manhua',
    'my school life pretending to be a worthless person': 'Manhwa',
    'my simulated path to immortality': 'Manhua',
    'my sister who was my enemy loves me': 'Other',
    'my sister, who was my enemy, loves me': 'Other',
    'my slain dragon bride': 'Manhwa',
    'my wife is actually the empress': 'Manhua',
    'my younger sister was a genius': 'Manhwa',
    'myst might mayhem': 'Manhwa',
    'nano machine': 'Manhwa',
    'nation class dungeon architect': 'Other',
    'nation-class dungeon architect': 'Other',
    'national level big shots flock to my farm': 'Other',
    'necromancer academys genius summoner': 'Manhwa',
    "never mind the heir i'll focus on healing": 'Manhwa',
    'never mind the heir, i’ll focus on healing': 'Manhwa',
    'ngoxhy': 'Other',
    'night at the crossroads': 'Other',
    'nightmare realm summoner': 'Manga',
    'noble lady reformation guide': 'Other',
    'now it’s your turn to regret': 'Manhwa',
    'nuclear explosion swordsmanship: one slash, one kill': 'Other',
    'oh! my maid': 'Manhwa',
    'omniscient reader’s viewpoint': 'Manhwa',
    'on a perfect revenge': 'Other',
    'on getting the power of god': 'Manhua',
    'one day, i became a hatchling.': 'Manhwa',
    'one piece': 'Manga',
    'one-of-a-kind irregular': 'Manhwa',
    'operation heart pounding': 'Manhwa',
    'operation heart-pounding': 'Manhwa',
    'outcast necromancer': 'Manhwa',
    'outlaws': 'Manhua',
    'overpowered sword': 'Manhwa',
    'oversummoned, overpowered, and over it!': 'Manga',
    'past life regressor [remake]': 'Manhwa',
    'past life returner 2022': 'Manhwa',
    'past lives of the thunder god': 'Manhwa',
    'path of the shaman': 'Manhwa',
    'pavane for the dead hunter': 'Manhwa',
    'pick me up : infinite gacha': 'Manhwa',
    'plastic sisters': 'Manhua',
    'player': 'Manhwa',
    'player who returned 10,000 years later': 'Manhwa',
    'please give me the pacifier': 'Manhwa',
    'pmu': 'Other',
    'pobstoez': 'Other',
    'poison dragon: the legend of an asura': 'Manhwa',
    'pokémon adventures': 'Manga',
    'post-apocalyptic dispatch company': 'Manhua',
    'pride of the blade': 'Manhwa',
    'raising villains the right way': 'Manhwa',
    'ranker who lives a second time': 'Manhwa',
    'rcd': 'Other',
    'reaper of the drifting moon': 'Manhwa',
    'rebirth monarch of the dead': 'Other',
    'rebirth of the divine demon': 'Manhwa',
    'rebirth: monarch of the dead': 'Manhua',
    'rebirth: my vengeance through the mirror': 'Other',
    'reborn as the heavenly demon': 'Manhwa',
    'reckless captain of the guard in a medieval fantasy': 'Other',
    'record of lodoss war: the necromancer queen': 'Other',
    'records of the swordsman scholar': 'Manhwa',
    'red shirt': 'Manhwa',
    'reformation of the deadbeat noble': 'Manhwa',
    'regressed genius creates mythic items': 'Manhwa',
    'regressing as the reincarnated bastard of the sword clan': 'Manhwa',
    'regressing with the king’s power': 'Manhwa',
    'regression of the yong clan heir': 'Manhwa',
    'reincarnated as a genius prodigy of a prestigious family': 'Manhwa',
    'reincarnated as a son of an aristocrat': 'Manga',
    'reincarnated as the weakest warrior with the power to choose any reward': 'Other',
    'reincarnated as the youngest son of a demon swordsman family': 'Other',
    'reincarnated escort warrior': 'Manhwa',
    'reincarnation of the fist king': 'Manhwa',
    'reincarnation of the heavenly demon': 'Manhwa',
    'reincarnation path of the underworld king': 'Manhwa',
    'reincarnator': 'Manhwa',
    'reincarnators stream': 'Manhwa',
    'reincarnator’s stream': 'Manhwa',
    'reset life of a game addict': 'Manhwa',
    'return of the 8th class magician': 'Manhwa',
    'return of the apocalypse class death knight': 'Manhwa',
    'return of the apocalypse-class death knight': 'Manhwa',
    'return of the bachelor': 'Manhwa',
    'return of the disaster-class hero': 'Manhwa',
    'return of the first generation': 'Other',
    'return of the first generation the strongest in history reincarnates as his descendant 1000 years later': 'Other',
    'return of the frozen player': 'Manhwa',
    'return of the hated black mage': 'Other',
    'return of the legendary spear knight': 'Manhwa',
    'return of the mount hua sect': 'Manhwa',
    'return of the reaper assassin': 'Other',
    'return of the runebound professor': 'Other',
    'revenge of the bloom flower': 'Manhwa',
    'revenge of the iron blooded sword hound': 'Manhwa',
    'revenge of the iron-blooded sword hound': 'Manhwa',
    'reverse villain': 'Manhwa',
    'riding on the edge of annihilation': 'Manhua',
    'rise from the rubble': 'Manhua',
    'rise of the demon king': 'Manhua',
    'rise of the devourer king': 'Manhua',
    'rise of the god slaying master': 'Other',
    'rise of the limitless necromancer': 'Manhua',
    'rise of the mushroom king': 'Manhua',
    'road to mastery': 'Other',
    'rogue of doom': 'Manhua',
    'rookie but one in a million actor': 'Manhwa',
    'rookie employee kim cheolsu': 'Manhwa',
    'rp': 'Other',
    'rust': 'Manhwa',
    'ryūgari no nato –dragon hunt tribe–': 'Other',
    's-class hunter heals with monsters': 'Other',
    'sandmancer of the scorched desert': 'Other',
    'sangeki': 'Manga',
    'saved by the powerless little lady': 'Manhwa',
    'saving the villain who was abandoned by the female lead': 'Manhwa',
    'secret family': 'Manhwa',
    'secretly more powerful than the hero': 'Manhwa',
    'serpent ancestor': 'Manhua',
    'shadow of the reborn rogues dominion': 'Other',
    'shadow slave': 'Manhwa',
    'shangri-la frontier': 'Manga',
    'she was sent for him': 'Other',
    "she wasn't my daughter": 'Manhwa',
    'she wasnt my daughter': 'Manhwa',
    'shingeki no kyojin': 'Manga',
    'sicario': 'Manhwa',
    "since i'm a time limited princess who has no tomorrow": 'Other',
    'since i’m a time-limited princess who has no tomorrow': 'Other',
    'single dad in another realm': 'Manhwa',
    'sir': 'Other',
    'skeleton soldier couldnt protect the dungeon': 'Manhwa',
    'skeleton soldier couldn’t protect the dungeon': 'Manhwa',
    'skeleton warrior': 'Manhwa',
    'sleeping ranker': 'Manhwa',
    'solmi solfa, my song': 'Manhwa',
    'solo bug player': 'Manhwa',
    'solo farming in the tower': 'Manhwa',
    'solo leveling': 'Manhwa',
    'solo leveling: ragnarok': 'Manhwa',
    'solo login': 'Manhwa',
    'solo max-level newbie': 'Manhwa',
    'sorry, my skills are automatically maxed out!': 'Manhua',
    'special contract marriage': 'Other',
    'spend more earn more': 'Other',
    'spend more, earn more': 'Other',
    'sss grade saint knight': 'Manhua',
    "sss-class assassin's return": 'Manhua',
    'standard of reincarnation': 'Manhwa',
    'star in the daytime': 'Manhwa',
    'star instructor, master baek': 'Manhwa',
    'star martial god technique': 'Manhua',
    'star-embracing swordmaster': 'Other',
    'start by signing in and obtaining the ancient divine body': 'Manhua',
    'starting as the black dragon boss i am invincible': 'Manhua',
    'starting with 13 hidden traits': 'Manhwa',
    'steel-eating player': 'Manhwa',
    'street restaurant of a returned hero': 'Manhwa',
    'strongest abandoned son (new)': 'Manhua',
    'strongest fighter': 'Manhwa',
    'strongest level 1': 'Manhwa',
    'study group': 'Manhwa',
    'super evolution': 'Manhua',
    'super god gene': 'Manhua',
    'super god pet beast shop': 'Manhua',
    'super nova': 'Manhwa',
    'superhuman battlefield': 'Manhwa',
    'superstar from age 0': 'Manhwa',
    'supreme curse master': 'Manhua',
    'supreme demon of hyungsan': 'Manhua',
    'supreme fair trade authority': 'Other',
    'supreme red packet emperor': 'Manhua',
    'supreme zerg lord': 'Manhua',
    'survivalism': 'Manhwa',
    'surviving as a genius on borrowed time': 'Other',
    'surviving in a school bully webtoon': 'Manhwa',
    'surviving in an rpg maker horror game': 'Other',
    'surviving in another world': 'Manga',
    'surviving the apocalypse': 'Manhwa',
    'surviving the game as a barbarian': 'Manhwa',
    'survivor story of a sword king in a fantasy world': 'Manhwa',
    'swallow the whole world': 'Manhua',
    'sword dance online': 'Manhua',
    'sword god high school the talentless underachiever becomes the strongest': 'Other',
    'sword god high school: the talentless underachiever becomes the strongest': 'Other',
    "sword god's livestream": 'Manhwa',
    "sword sheath's child": 'Manhwa',
    "swordmaster's youngest son": 'Manhwa',
    'swordsman of sichuan tang family': 'Other',
    'tale of a scribe who retires to the countryside': 'Manhwa',
    'talent-swallowing magician': 'Manhwa',
    'tales of demons and gods': 'Manhua',
    'taming master': 'Manhwa',
    'tengoku daimakyou': 'Manga',
    'tenkaichi: nihon saikyou bugeisha ketteisen': 'Manga',
    'territory defense with tamed monsters': 'Manga',
    'test manga 3': 'Other',
    'tgmra4000y': 'Other',
    'the 100th regression of the max-level player': 'Manhwa',
    'the 31st piece turns the tables': 'Manhwa',
    'the abyssal seed': 'Manhua',
    'the academy’s sashimi sword master': 'Manhwa',
    'the age of arrogance': 'Manhwa',
    'the apocalypse has come': 'Manhwa',
    'the apocalypse needs a pro': 'Manhwa',
    'the archduke’s flower is in jeopardy': 'Other',
    "the archmage's restaurant": 'Manhwa',
    'the art of leaving work on time': 'Other',
    'the avenging assassin doll': 'Other',
    'the baby raising a devil': 'Manhwa',
    'the back-alley mage’s return': 'Other',
    'the baddest villainess is back': 'Manhwa',
    'the bat knight: dan': 'Other',
    'the blood princess and the knight': 'Manhua',
    'the book eating magician': 'Manhwa',
    'the butcher blade that pierces all realms': 'Manhua',
    'the calamity prince wants the fake princess': 'Other',
    'the care alliance': 'Other',
    'the chairman of pharmaceutical company is a poison king': 'Manhwa',
    'the chairman who just wants to slack off': 'Manhwa',
    'the cleaners agent': 'Manhwa',
    'the constellations are my disciples': 'Manhwa',
    'the corruption-immune swordsman’s calamity sword': 'Other',
    "the count's secret maid": 'Manhwa',
    "the count's youngest son is a player": 'Manhwa',
    'the counts youngest son is a player': 'Manhwa',
    'the crown prince that sells medicine': 'Manhwa',
    'the dark mage’s return to enlistment': 'Manhwa',
    'the dark swordsman returns': 'Manga',
    'the delivery man from murim': 'Manhwa',
    'the demon king overrun by heroes': 'Manhwa',
    'the demon king who lost his job': 'Manhua',
    'the demonic cult instructor returns': 'Manhwa',
    'the demonic cult leader is too reluctant': 'Manhwa',
    'the descent of the demonic master': 'Manhwa',
    'the diary of loving a forgetful sweet wife': 'Manhua',
    'the divine ring descends the strongest otherworld': 'Manhua',
    'the divine ring descends: the strongest otherworld': 'Manhua',
    'the dragon of kunlun': 'Other',
    'the duchess with an empty soul': 'Manhwa',
    'the duke needs home education': 'Other',
    'the dungeon painter': 'Manhwa',
    'the dutiful kid who saved the villainous family': 'Other',
    'the empire’s villainess': 'Other',
    'the eternal calamity': 'Other',
    'the eternal supreme': 'Manhua',
    'the extras academy survival guide': 'Manhwa',
    'the extra’s academy survival guide': 'Manhwa',
    'the father and the daughter': 'Manhwa',
    'the final boss became a player': 'Manhua',
    'the final boss wants to die': 'Other',
    'the forgotten field': 'Manhwa',
    'the forgotten fields': 'Manhwa',
    'the fox-eyed villain of the demon academy': 'Manhwa',
    'the genius assassins second life at the academy': 'Other',
    'the genius midfielders passes are special': 'Manhwa',
    'the genius wants to be ordinary': 'Other',
    'the genius who reads the world': 'Other',
    'the glutton': 'Manhua',
    'the god of war is leveling up': 'Manhwa',
    'the goddess of fortune': 'Manhwa',
    'the golden haired elementalist': 'Manhwa',
    "the grand duke's new daughter in law is a little fierce": 'Other',
    'the grand duke’s new daughter-in-law is a little fierce': 'Other',
    'the great mage returns after 4000 year s': 'Manhwa',
    'the great mage returns after 4000 years': 'Manhwa',
    'the heavenly demons apocalypse': 'Other',
    'the hero starts over at the academy': 'Manga',
    "the heroine's sister-in-law in a childcare story": 'Manhwa',
    'the holy power of modern medicine': 'Manhwa',
    'the illegitimate who devours weapons': 'Manhwa',
    'the imperial maiden': 'Manhwa',
    'the indomitable martial king': 'Manhwa',
    'the investor who sees the future': 'Manhwa',
    'the iron and ice journey': 'Manhwa',
    'the iron-blooded necromancer has returned': 'Manhwa',
    'the jinxs strategy for domination': 'Other',
    'the joseon prince went to america and didnt return': 'Manhwa',
    'the killer lawyer': 'Manga',
    'the king of snow': 'Manhua',
    'the king of the special forces': 'Manhua',
    'the lady is a stalker': 'Manhwa',
    'the last adventurer': 'Manhwa',
    'the last golden child': 'Manhwa',
    'the last summoner': 'Manhua',
    'the legend of the twin dragons': 'Manhua',
    'the legendary assassin reincarnated as the beloved youngest daughter': 'Manga',
    'the legendary hero is an academy honors student': 'Manhwa',
    'the legendary moonlight sculptor': 'Manhwa',
    'the level 9999 underachiever dominates in a woman ruled world': 'Other',
    'the little bear in the black fox mansion': 'Other',
    'the little brother is the academy’s hotshot': 'Other',
    'the lord of money': 'Manhwa',
    'the lord who levels up by absorbing powers': 'Other',
    'the lord who levels up by devouring': 'Manhwa',
    'the lords coins arent decreasing': 'Manhwa',
    'the low ranking civil servant wants to achieve success': 'Other',
    'the mad dog of the duke’s estate': 'Manhwa',
    "the magic tower's problem child": 'Manhwa',
    'the maid with a child': 'Manhwa',
    'the main characters that only i know': 'Manhwa',
    'the main heroines are trying to kill me': 'Manhwa',
    'the male lead is obsessed with my health': 'Manhwa',
    'the mansion awaits spring': 'Manhwa',
    'the mansion awaits spring1': 'Manhwa',
    'the martial genius who remembers everything': 'Manhwa',
    'the max leveled hero will return': 'Manhwa',
    'the memoir of a certain evil wizard': 'Other',
    'the misfit of the martial world': 'Other',
    'the moon witch and the sun king: my salvation': 'Manhwa',
    'the mysterious world’s greatest martial artist little prince': 'Other',
    'the mythical realm': 'Manhua',
    "the necromancer family's young heir": 'Manhwa',
    'the ninth-rank sword master': 'Manhwa',
    'the nis rookie': 'Other',
    "the novel's extra": 'Manhwa',
    'the novels extra 2': 'Manhwa',
    'the novel’s extra': 'Manhwa',
    "the novice's frontline": 'Other',
    'the obsessive maniacs is trying to confine': 'Other',
    'the old man swears vengeance against his demonic wife': 'Other',
    'the oracle of the villainous baby': 'Manhwa',
    'the oracle of the villainous baby1': 'Manhwa',
    'the over invested unrequited crush club': 'Other',
    'the over-invested unrequited crush club': 'Other',
    'the path toward heaven': 'Manhua',
    'the peaceful life of a maid who hides her power and enjoys it': 'Manhwa',
    'the peerless concubine': 'Manhua',
    'the player hides his past': 'Manhwa',
    'the player of the fallen family': 'Manhwa',
    'the politician who can see the future': 'Other',
    'the priest of corruption': 'Manhwa',
    'the princess wants to die comfortably': 'Manhwa',
    'the princess who returned by dying became the tyrants personal chef': 'Other',
    'the princess who returned by dying became the tyrant’s personal chef': 'Other',
    'the problematic children of the magic tower': 'Other',
    'the ravages of time (rot)': 'Manhua',
    'the rebel of the tyrant noble family': 'Other',
    'the red king': 'Other',
    "the regressed mercenary's machinations": 'Manhwa',
    'the regressed son of a duke is an assassin': 'Manhwa',
    'the reincarnated assassin is a genius swordsman': 'Manhwa',
    'the reincarnation magician of the inferior eyes': 'Manga',
    'the return of apocalypses tyrant': 'Manhwa',
    'the return of senior disciple lee hoo': 'Other',
    'the return of the crazy demon s': 'Manhwa',
    'the return of the musical genius': 'Other',
    'the return of the s-rank holy weapon user from the duke’s family': 'Manga',
    'the return of the unrivaled genius ranker': 'Other',
    'the returnees hidden strategy stream': 'Manhwa',
    'the returners road to retirement': 'Manhwa',
    'the reversal of my life as a side character': 'Manga',
    'the road of karma': 'Manhwa',
    'the ruined world was mistaken for a game': 'Manhwa',
    'the ruler of darkness': 'Manhwa',
    'the saint levels up through necromancy': 'Other',
    'the scorched desert’s sand mage': 'Other',
    'the second eunuch regains his manhood': 'Manhwa',
    'the serpent of paradise': 'Manhwa',
    'the seventh prince wants to bail': 'Manhwa',
    'the shepherd wizard': 'Manhwa',
    'the sorcerer king of destruction and the golem of the barbarian queen': 'Manga',
    'the steel emperor': 'Manhwa',
    'the story of a low-rank soldier becoming a monarch': 'Manhwa',
    'the strongest reincarnated as a mediocre heir of a prestigious family': 'Other',
    'the strongest romantic': 'Manhwa',
    'the strongest swordsman rising from a bottom tier job': 'Other',
    'the strongest swordsman rising from a bottom-tier job': 'Other',
    'the substitute hero': 'Manhwa',
    'the summer swallowed by darkness': 'Manhwa',
    'the superhuman era': 'Manhwa',
    'the support ate it all': 'Manhwa',
    'the supreme demonic sword': 'Manhwa',
    'the supreme poison demon becomes a pharma chairman': 'Manhwa',
    'the sword emperor who surpasses his previous life': 'Other',
    'the sword saint reincarnated into a noble mage family': 'Other',
    'the tale of cultivation and demon extermination': 'Other',
    'the tang clan chronicles': 'Manhwa',
    'the terminally ill young master of the baek clan': 'Manhwa',
    'the theory of useless magic': 'Manhua',
    'the timid frontier heiress never gives up her revenge': 'Other',
    'the top player returns': 'Manhua',
    "the top ranker's aspiring writer life manual": 'Manhwa',
    'the tutorial is too hard': 'Manhwa',
    'the tyrant girl neros rebellion': 'Other',
    'the ultimate prodigy': 'Other',
    'the ultimate shut-in': 'Manhwa',
    'the undefeatable swordsman': 'Manhwa',
    'the underworld transcendent is unrivaled at the school': 'Manga',
    "the underworld's broker": 'Other',
    'the veteran healer is too strong': 'Other',
    'the veteran swordmasters stream': 'Manhwa',
    'the villain wants to live': 'Manhwa',
    'the villainess captured the male lead': 'Other',
    'the villainess sister hides her wealth': 'Manhwa',
    'the villainous sister hides her wealth': 'Manhwa',
    'the villains match is too perfect': 'Manhwa',
    'the villainss favourite is me': 'Manhwa',
    'the wandering knights survival manual': 'Manhwa',
    'the wandering knight’s survival manual': 'Manhwa',
    'the weakest occupation "blacksmith," but it\'s actually the strongest': 'Manga',
    "the well-mannered husband's motive for marriage is suspicious": 'Other',
    'the world after the fall': 'Manhwa',
    "the world's best engineer": 'Manhwa',
    'the worlds best martial arts instructor': 'Manhwa',
    'the world’s best martial arts instructor': 'Manhwa',
    'the youngest daughter of the great magician of a famous swordsmanship family': 'Other',
    'the youngest filming a childcare reality show is adorable': 'Other',
    'the youngest son of a conglomerate': 'Manhwa',
    'the youngest son of the eunhae merchant group': 'Manhwa',
    'the zenith': 'Manhwa',
    'there is no place for fakes': 'Manhwa',
    'theres no such thing as a bad hero in the world': 'Other',
    'there’s no such thing as a bad hero in the world': 'Manhwa',
    'third rate martial family becomes the best under heaven': 'Manhwa',
    'this assassin is upright': 'Manhua',
    'this is an obvious fraudulent marriage': 'Manhwa',
    'this is the law': 'Manhwa',
    'this killer is a son in law': 'Manhua',
    'this witch of mine': 'Manhwa',
    'tigers': 'Manga',
    'to hell with being heir im going to heal': 'Manhwa',
    'to hell with the status window': 'Manhwa',
    'to my sweetheart': 'Manga',
    'to not die': 'Manhwa',
    'transcendence due to a system error': 'Manhwa',
    'trapped in a crazy world as an extra': 'Manhwa',
    'trash of the count’s family': 'Manhwa',
    'true martial world': 'Manhua',
    'turns out im a third generation chaebol': 'Manhwa',
    'umineko episode 1 legend of the golden witch': 'Manga',
    'umineko no naku koro ni chiru episode 7 requiem of the golden witch': 'Manga',
    'umineko no naku koro ni chiru episode 8 twilight of the golden witch': 'Manga',
    'underworld monarch i am the abyss': 'Manhua',
    'underworld restaurant': 'Manhwa',
    'unrivaled spear demon': 'Manga',
    'urban dragon war': 'Manhua',
    'using my cooking skills in a murim world': 'Manhwa',
    'vagabond': 'Manhua',
    'vanitas no carte': 'Manga',
    'versatile mage': 'Manhua',
    "villain family's strongest butler": 'Manga',
    'villain is here': 'Manhua',
    "violet's last word": 'Other',
    'violet’s last word': 'Other',
    'vote for your knight!': 'Manhwa',
    'wae': 'Other',
    'warrior grandpa and supreme granddaughter': 'Manhwa',
    'warrior high school – dungeon raid department': 'Manhwa',
    "wasn't i the female lead of a regret novel?": 'Other',
    'watashi no shiawase na kekkon': 'Manga',
    'wbe': 'Other',
    'weryre': 'Other',
    'wfjsra': 'Other',
    'what happens when a dying secret agent moves to the countryside': 'Other',
    'when a genius office worker goes too far': 'Manhwa',
    'why would a villainess have virtue?': 'Manhwa',
    'wild ranker': 'Manhwa',
    'wild west murim': 'Manhwa',
    'wind breaker': 'Manga',
    'winter carnival': 'Manhwa',
    'wish': 'Manhwa',
    'wonderland': 'Manga',
    'world saving is a skill': 'Manhwa',
    "world's strongest survivor": 'Manhwa',
    'world’s greatest senior disciple': 'Manhwa',
    'world’s ruler': 'Manhua',
    'worn and torn newbie': 'Manhwa',
    'wrecker driver': 'Manhwa',
    'xian ni': 'Manhua',
    'xqnzna': 'Other',
    'y5yadw8hjmcpur': 'Other',
    'young lady is a royal chef': 'Manhwa',
    'youngest scion of the mages': 'Manhwa',
    'zero level hero': 'Other',
    'zombie apocalypse 82 08': 'Manhwa',
    'مانغا': 'Other',
    'معجزة ونبوءة': 'Other',
    '\u200feverlasting longing': 'Other',
    "\u200fi'm a sickly mother, but i'll raise my villainous son!": 'Manga',
    '\u200fi’m a former office worker reborn as the villainess of the apocalypse': 'Other',
    '\u200fnearby muscle girl': 'Manga',
}

GENRES = {
    '+99 wooden stick': [],
    '1/24 romance': ['Romance', 'Comedy'],
    '100 million years later: the ultimate weapon’s return': [],
    "18-year-old villainess' target": [],
    '2072267132 call of the spear': [],
    '2072267132 doomsday for all me virus monarch': [],
    '2072267132 i picked a hammer to save the world': [],
    '2072267132 im really not the devils lackey': [],
    '2072267132 logging 10 000 years into the future': [],
    '2072267132 necromancer academys genius summoner': ['Action', 'Romance', 'Adventure', 'Fantasy'],
    '2072267132 start by signing in and obtaining the ancient divine body': ['Action', 'Comedy', 'Wuxia', 'Isekai', 'Drama', 'Fantasy'],
    '2072267132 super god pet beast shop': [],
    '2072267132 the eternal supreme': [],
    '30 years since the prologue': [],
    '404 case manual: 30 seconds till apocalypse': ['Thriller', 'Sci-Fi', 'Horror'],
    'a baby dragon saves the dukedom': [],
    'a barbarian’s adventure in a fantasy world': [],
    'a blank slate regression for the idol that lost his original mindset': ['Drama', 'Fantasy', 'Slice of Life'],
    'a butchers cleaver can topple the myriad realms right': [],
    'a cadet becomes a prophet': ['Action', 'Drama', 'Fantasy'],
    'a corporate underling who excels at work': ['Drama', 'Slice of Life'],
    "a dragonslayer's peerless regression": ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'a dragonslayers peerless regression': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'a fortune-telling princess': [],
    'a glimpse of the jianghu': ['Historical', 'Action', 'Drama', 'Fantasy'],
    'a love that crosses the line': ['Comedy', 'Drama'],
    'a mercenary’s rebirth among nobles': [],
    'a modern man who got transmigrated into the murim world': [],
    'a painter who draws dungeons': [],
    'a saint who was adopted by the grand duke': ['Romance', 'Fantasy'],
    'a sister must raise her younger sister properly': [],
    'a spys survival in the demonic cult': [],
    'a strange life': ['Romance', 'Comedy', 'Drama', 'Fantasy'],
    'a wimps strategy guide to conquer the tower': [],
    'a wimp’s strategy guide to conquer the tower': [],
    'absolute domination at level 0 using my analysis skill': [],
    'absolute scholar': ['Historical', 'Action', 'Drama'],
    'absolute sword sense': [],
    "academy's genius swordmaster": [],
    'after million of years i woke up to be a god': ['Action', 'Adventure', 'Fantasy'],
    'after rebirth, i used mirror reversal for vengeance': [],
    'after the possessor left1': [],
    'against the gods': [],
    'ags': [],
    'algd almharb oalhfyd alaalya': [],
    'all hail the sect leader': [],
    'all my alter egos are tycoons': [],
    'all people scramble for the tower: i cleared 999 floors in advance': ['Thriller', 'Action', 'Adventure', 'Mystery'],
    'all rounder': ['Action', 'Sports', 'Drama', 'Slice of Life'],
    'altragaa bko almlk': [],
    'an art student who lives twice': ['Drama'],
    'an extra who wants to escape the obsessive male lead': [],
    'an unparalleled martial arts spirit': [],
    'ancient teacher': [],
    'ankle breaker': [],
    'annihilation of the heavenly way': [],
    'apocalypse mechanic': [],
    'apocalypse sword god i shock the world': [],
    'apocalyptic chef awakening': ['Action', 'Adventure'],
    'apocalyptic heat i became a god using my safe house': [],
    'apotheosis': ['Action', 'Horror'],
    'archmage curriculum': ['Action', 'Horror', 'Fantasy'],
    'archmage transcending through regression': ['Action', 'Adventure', 'Fantasy'],
    'aristocrats revenge': [],
    'artifact reading appraiser': ['Wuxia', 'Drama', 'Fantasy'],
    'artifact-devouring player': ['Action', 'Adventure', 'Fantasy'],
    "askr yggdrasil's wood": ['Sci-Fi', 'Action', 'Adventure'],
    'at the abyss of fall i find you': [],
    'at the abyss of fall, i find you': [],
    'auto hunting with my clones': ['Action', 'Adventure', 'Fantasy'],
    'awakening the purple thunder at the beginning': [],
    'baby prisoner of the winter castle': ['Romance', 'Fantasy'],
    'baby squirrel is good at everything': [],
    'back to rule again': [],
    'back to the city: the strongest investment king': [],
    'baki rahen': [],
    'bate': [],
    'became a medieval fantasy wizard': [],
    'becoming a legendary ace employee': [],
    'becoming an immortal official starts with transmigrating as a hog': [],
    "becoming the cheon clan's mad dog": [],
    'begin': ['Action', 'Crime', 'Drama'],
    'behind the laughter of the surviving princess': [],
    'berserk': ['Action', 'Psychological', 'Adventure', 'Philosophical', 'Drama', 'Horror', 'Fantasy', 'Tragedy'],
    'black corporation: joseon': ['Historical', 'Fantasy'],
    'black killer whale baby': [],
    'black man ill do everything for you except marriage': [],
    'blade debt': ['Action', 'Comedy', 'Wuxia', 'Drama', 'Fantasy'],
    'blades of the guardians': [],
    'blocking monsters with monsters': [],
    'blood breakrr': [],
    'blood system': [],
    'bones': ['Thriller', 'Action', 'Psychological', 'Crime', 'Adventure', 'Fantasy', 'Tragedy'],
    'boss beating': [],
    'boundless necromancer': [],
    'bungou stray dogs: dazai wo hirotta hi': [],
    'call of the spear': [],
    'capital’s most crazy doctor': ['Action', 'Romance', 'Medical'],
    'carrying the goddess along': [],
    'castle': ['Action', 'Crime', 'Drama', 'Tragedy'],
    'cataclysm hunter: i have an experience points system': [],
    'catastrophic necromancer': [],
    'celebrity lady': ['Romance', 'Comedy', 'Drama', 'Fantasy'],
    'ceres the time healer': [],
    'ceres, the time healer': [],
    'charlotte has five disciples': ['Romance', 'Comedy', 'Drama', 'Fantasy', 'Mystery'],
    'chat with me': [],
    'childhood friend of the zenith': [],
    'children of the rune': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'chronicle of runes': [],
    'chronicles of the absolute song sect': [],
    'chronicles of the demon faction': ['Action', 'Drama', 'Fantasy'],
    'chronicles of the lazy sovereign': ['Action', 'Drama', 'Fantasy'],
    'chronicles of the moonlit night': [],
    'chrono labyrinth': [],
    'classmates': ['Romance', 'Drama', 'Slice of Life'],
    'cm': [],
    'coffe thief': ['Romance', 'Adventure', 'Fantasy'],
    'concept grasping magic genius': [],
    'cosmic heavenly demon 3077': ['Sci-Fi', 'Action', 'Comedy', 'Wuxia', 'Fantasy'],
    'crimson reset': [],
    'cultivator against hero society': [],
    'damn demonic swords': [],
    'damn reincarnation': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'dare i hope': ['Romance', 'Drama', 'Fantasy'],
    'dark and light martial emperor': [],
    'dch': [],
    'dearest fiance i know you despise me': [],
    'death is the only ending for the villainess': [],
    'defiance of the fall': ['Action', 'Fantasy'],
    'demon god reincarnation': ['Action', 'Drama'],
    'demonic emperor': [],
    'detective conan': ['Action', 'Psychological', 'Romance', 'Comedy', 'Crime', 'Adventure', 'Drama', 'Mystery'],
    'devil summoner i am the abyss lord': [],
    'disaster comes i evolve in to the crimson king': [],
    'divine spirit': [],
    'dog eat dog': ['Isekai', 'Fantasy'],
    'doom summoner': ['Action', 'Adventure', 'Fantasy'],
    'doomsday arrival: evolution into the crimson king': ['Action', 'Adventure', 'Fantasy'],
    'doomsday for all me virus monarch': [],
    'dr. hound': ['Thriller', 'Psychological', 'Drama', 'Horror', 'Mystery'],
    'dragon-devouring mage': [],
    'dream cycle reincarnation: i became the supreme martial king': [],
    'duke pendragon': [],
    'dukedom’s legendary prodigy': [],
    'dumped by my girlfriend so i turned to martial arts': ['Thriller', 'Action', 'Adventure', 'Fantasy'],
    'dungeon athlete': [],
    'dungeon defense': ['Action', 'Psychological', 'Romance', 'Isekai', 'Drama', 'Fantasy'],
    'dusk divide': [],
    'ebony': ['Romance', 'Drama', 'Fantasy'],
    'ebony 3': [],
    'ecd': [],
    'egflbroj': [],
    'emperor and the female knight': [],
    'emperor of solo play': ['Sci-Fi', 'Action', 'Adventure', 'Drama', 'Fantasy'],
    'en travesti – i became a fake prince': ['Romance', 'Drama', 'Fantasy'],
    'enigmatica': ['Thriller', 'Historical', 'Psychological'],
    'entomologist in sichuan tang clan': [],
    'eternal kingdom': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'even madness strikes thrice': [],
    'everlasting longing': [],
    'everyone was obsessed with me after i became the youngest princess favourite': ['Romance', 'Fantasy'],
    'everything was a mistake': [],
    'evolution begins with a big tree': [],
    'executioner': ['Action', 'Fantasy'],
    'extracted into the god of necromancy': [],
    'f-class destiny hunter': ['Action', 'Fantasy'],
    'fantasy induction corps': [],
    'fated to be loved by villains': ['Action', 'Romance', 'Comedy', 'Isekai', 'Fantasy'],
    'father, i don’t want to get married!': ['Historical', 'Romance', 'Isekai', 'Drama', 'Fantasy'],
    'feasting lord in another world': ['Comedy', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'fechippuru ~our innocent love.': [],
    'festival of warriors': [],
    'fff-class trashero': ['Action', 'Comedy', 'Adventure', 'Isekai', 'Fantasy'],
    'for my gentle monster': [],
    'free in dreams': [],
    'from child actor to global superstar!': [],
    'from disgraced lady to beloved stepmother': [],
    'frozen frontiers': [],
    'full time awakening': [],
    'full time hunter i hunt the world': [],
    'full-time awakening': [],
    'full-time hunter: i hunt the world!': [],
    'game obu familia - family senki': ['Action', 'Psychological', 'Romance', 'Adventure', 'Isekai', 'Drama', 'Horror', 'Fantasy'],
    'gangnam sink': [],
    'gatekeeper of the boundless world': ['Action', 'Horror'],
    'genius archer’s streaming': ['Action', 'Sports', 'Adventure'],
    'genius martial arts trainer': [],
    'ghosting groom': [],
    'gizmo riser': [],
    'glass wall': [],
    'global beast tamer i can see the path of evolution': [],
    'global class awakening the mage kings skills gain infinite upgrades': [],
    'global game i can have 100 fold amplification': [],
    'global job change starting with the hidden class necromancer lord': [],
    'global job change: starting with the hidden class necromancer lord': [],
    'glory': [],
    'go deok chuns food truck': ['Romance', 'Comedy', 'Drama', 'Slice of Life'],
    'goblin corporation': [],
    'goblin inc': [],
    'god of martial arts': ['Action', 'Romance', 'Isekai', 'Drama', 'Fantasy'],
    'golden mage': ['Isekai', 'Fantasy'],
    'golden martial god': [],
    'goodbye ex husband': [],
    'goodbye, ex-husband': [],
    'got dropped into a ghost story': ['Thriller', 'Action', 'Psychological', 'Adventure', 'Drama', 'Horror', 'Mystery'],
    'got dropped into a ghost story, still gotta work': ['Thriller', 'Action', 'Psychological', 'Adventure', 'Drama', 'Horror', 'Mystery'],
    'got dropped into a horror story, still gotta work': ['Thriller', 'Action', 'Psychological', 'Adventure', 'Drama', 'Horror', 'Mystery'],
    'grand general': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'greatest boss system': [],
    'green skin': [],
    'greet the sect leader': [],
    'guard pass': ['Action', 'Drama'],
    'haikyuu oneshot': [],
    'happy face from slave to arena legend': ['Action', 'Comedy', 'Adventure'],
    "harvest governor's envoy": [],
    'hataraku maou sama': ['Romance'],
    'hazure skill "kage ga usui" o motsu guild shokuin ga, jitsuha densetsu no ansatsusha': [],
    'healing at the academy convenience store': [],
    'healing life through camping in another world': [],
    'heavenly demon cultivation simulation': ['Action', 'Adventure', 'Wuxia', 'Drama', 'Fantasy'],
    'heavenly demon tavern': ['Historical', 'Action', 'Comedy', 'Adventure', 'Fantasy'],
    'heavenly demon wants to be a chef': ['Action', 'Adventure', 'Fantasy'],
    'heavenly grand archive’s young master': [],
    'heavenly inquisition sword': ['Action', 'Adventure'],
    'heavenly martial god': ['Historical', 'Action', 'Adventure', 'Fantasy'],
    'heir of mythical heroes': [],
    'hello griffin the fluffy bird': ['Comedy', 'Fantasy'],
    'hello mr. veterinarian!': [],
    'hellogin': [],
    'hero of all trades': ['Sci-Fi', 'Action', 'Drama', 'Fantasy'],
    'heroes of the imjin war': [],
    'high martial world with one hand he sweeps aside three thousand emperors': [],
    'high society': ['Drama'],
    'high-martial world: with one hand he sweeps aside three thousand emperors!': [],
    'horror rpg maker survival story': [],
    'how i became a married man in another world': [],
    'how the sword emperor establishes the namgung clan': [],
    'how to fight': [],
    'how to live as a civil servant in murim': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'how to live as an unlicensed healer': [],
    'how to save a time limited young master': [],
    'how to survive as the daughter of the emperor who killed me': [],
    'how to survive as the devils daughter': [],
    'how to turn you around': ['Romance', 'Comedy'],
    'hunter academys battle god': [],
    "hunter world's gardener": [],
    'hunter x hunter': ['Action', 'Psychological', 'Adventure', 'Philosophical', 'Drama', 'Horror', 'Fantasy', 'Mystery', 'Tragedy'],
    'hunter x hunter colored': ['Action', 'Psychological', 'Adventure', 'Philosophical', 'Drama', 'Horror', 'Fantasy', 'Mystery', 'Tragedy'],
    "i am in a secret relationship with the emperor, but i don't know it": [],
    'i am the fated villain': [],
    'i awoke as a god after auto battling for a million years': [],
    'i became a genius in sales': [],
    'i became a victim of the king of the wolves': [],
    'i became the daughter of a million-dollar actor': [],
    'i became the genius bastard of a noble dark clan': ['Drama', 'Fantasy'],
    'i became the king by scavenging': [],
    'i became the leader of a cursed idol groupe': [],
    'i became the master of the weakest demon king': [],
    'i became the rogue first prince': [],
    'i became the successor of the martial god': [],
    'i became the tyrant of a defense game': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    "i became the tyrant's time limited wife": ['Romance', 'Isekai', 'Fantasy'],
    'i became the tyrants servant': ['Historical', 'Romance', 'Isekai', 'Fantasy'],
    'i became the tyrant’s servant': ['Historical', 'Romance', 'Isekai', 'Fantasy'],
    'i became the tyrant’s time-limited wife': ['Romance', 'Isekai', 'Fantasy'],
    'i became the wife of the male lead': [],
    'i became the youngest prince in the novel': ['Action', 'Adventure', 'Fantasy'],
    'i became the youngest sister in law of the male leads ruined harem': [],
    'i become a hatchling': [],
    'i become a legendary arch mage by reading a book': [],
    'i become the youngest disciple of the martial arts leader': [],
    'i can snatch 999 types of abilities read': [],
    'i contracted myself': [],
    'i dont want to be a magip bridge': ['Romance', 'Isekai', 'Fantasy'],
    'i ended up raising my younger self': [],
    'i gave up being stronger': [],
    'i have a shanzhai': [],
    'i have an sss-rank trait, but i want a normal life': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'i have six months to live, but i’ve captivated the tyrant emperor': [],
    'i kidnapped the youngest daughter of the sichuan tang clan': [],
    'i long for your despair': [],
    'i married the dragon i killed': [],
    "i only need the duke's child": [],
    'i opened the era of mythical beasts': [],
    'i picked a hammer to save the world': [],
    'i really dont want to learn forbidden spells': ['Action', 'Adventure', 'Fantasy'],
    'i received a request from the villain boss': [],
    'i regressed to my ruined family': [],
    'i reincarnated as a legendary surgeon': ['Historical', 'Action', 'Adventure', 'Drama', 'Medical', 'Fantasy'],
    'i reincarnated as a villainess but why did i become a cat butler instead': ['Romance', 'Comedy', 'Isekai', 'Drama', 'Fantasy'],
    'i reincarnated as a villainess, but why did i become a cat butler instead?': ['Romance', 'Comedy', 'Isekai', 'Drama', 'Fantasy'],
    'i reincarnated as the crazed heir': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'i reincarnated as the daughter of a runaway sub heroine': [],
    "i saved you, but i'm not responsible": [],
    'i shall seal the heavens 2025': ['Action', 'Romance', 'Comedy', 'Adventure', 'Wuxia', 'Drama', 'Fantasy'],
    "i tamed my ex-husband's mad dog": ['Romance', 'Fantasy'],
    'i told you to farm but you became an emperor': [],
    'i took over the system players': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'i was immediately mistaken for a monster genius actor': [],
    'i was stuck on the same day for 3,000 years': ['Action', 'Adventure'],
    'i was thrown into an unknown manga': [],
    'i was trash': [],
    'i watched a play': [],
    'i will raise this family to greatness': ['Comedy', 'Drama', 'Fantasy'],
    'i will try to raise the villain properly': [],
    "i'm a beginner, but i'm actually the strongest level 99 player": [],
    "i'm a former office worker reborn as the villainess of the apocalypse": [],
    "i'm a sickly mother but i'll raise my villainous son!": ['Romance', 'Isekai', 'Fantasy'],
    "i'm a young system won't you raise m": [],
    "i'm a young system, won't you raise me?": [],
    "i'm being chased by my husband": ['Romance', 'Drama', 'Fantasy'],
    "i'm looking for a new husband": ['Romance', 'Drama', 'Fantasy'],
    "i'm the youngest disciple of the murim's mastermind": [],
    "i'm trying to become part of the dark duke's family": [],
    'if ai rules the world': ['Sci-Fi', 'Drama'],
    'ill retire after saving the world': [],
    'im a beginner but im actually the strongest level 99 player': [],
    'im a homebody but i possessed a depraved confinement novel': [],
    'im a villainess but im favored': [],
    'im being chased by my husband': ['Romance', 'Drama', 'Fantasy'],
    'im going to destroy this country': ['Action', 'Drama', 'Fantasy'],
    'im gonna annihilate this land': [],
    'im looking for a new husband': ['Romance', 'Drama', 'Fantasy'],
    'im really not the devils lackey': ['Thriller', 'Sci-Fi', 'Action', 'Comedy', 'Isekai', 'Fantasy', 'Mystery'],
    'im the tyrant familys beloved baby': [],
    'immortal swordsman in the reverse world': ['Action', 'Romance', 'Comedy', 'Adventure', 'Wuxia', 'Fantasy'],
    'immortals way of life': ['Action', 'Adventure', 'Fantasy'],
    'imperfect sister': [],
    'in': [],
    'in the shadow of the spring': [],
    'in this life, i will be the lord': [],
    'infinite breakthrough': [],
    'infinite level up in murim': ['Action', 'Adventure', 'Fantasy'],
    'infinite mage': ['Action', 'Adventure', 'Fantasy'],
    'insanely-talented player': [],
    'interspecies protection agency': ['Action', 'Romance', 'Drama', 'Fantasy'],
    'invasion of the myriad races starting by taming a legendary beast': ['Action', 'Adventure'],
    'inverse scale': [],
    "is it bad that the main character's a roleplayer": [],
    'is it bad that the main character’s a roleplayer': [],
    'isnt being a wicked woman much better': ['Romance', 'Comedy', 'Isekai', 'Drama', 'Fantasy'],
    'isnt this inside the game': ['Adventure', 'Drama', 'Fantasy'],
    'it all starts with playing game seriously': ['Action'],
    'its jiyujiyo': [],
    'i’ll be taking a break for personal reasons': ['Action', 'Drama', 'Fantasy'],
    'i’m going to destroy this country': ['Action', 'Drama', 'Fantasy'],
    'i’m not that kind of talent': ['Action', 'Comedy', 'Adventure', 'Drama', 'Fantasy'],
    'i’m really not a demon lord': [],
    'i’m trying to become part of the dark duke’s family': [],
    'i’m using the hero to servive!': [],
    'jackpot after divorce': ['Romance', 'Drama', 'Slice of Life'],
    'judgment': ['Thriller', 'Action', 'Psychological', 'Drama', 'Mystery', 'Tragedy'],
    'jungle juice': ['Sci-Fi', 'Action', 'Superhero', 'Fantasy'],
    'kaijuno8': [],
    'kaiten no albus': [],
    'kamisama ni kago 2 nin bun moraimashita': [],
    'kengan ashura': ['Thriller', 'Action', 'Psychological', 'Comedy', 'Crime', 'Sports', 'Drama'],
    'kengan omega': ['Action', 'Drama'],
    'kidnapped by the earth': ['Action', 'Wuxia', 'Drama', 'Fantasy'],
    'kidnapped dragons': [],
    'kill the dragon': ['Action', 'Mecha', 'Adventure', 'Drama', 'Fantasy'],
    'killer pietro': ['Action', 'Crime', 'Drama'],
    'killing guard': [],
    'king of the cartel': [],
    'kingdom': ['Historical', 'Action', 'Drama'],
    'kingdom (wan)': ['Historical', 'Action', 'Drama'],
    'kingdom hearts': ['Thriller', 'Action', 'Psychological', 'Comedy', 'Adventure', 'Drama', 'Fantasy', 'Tragedy'],
    'kot': [],
    'kouryakuhon o kushi suru saikyou no mahoutsukai ~ to wa iwa senai oreryuu mao tobatsu saizen ruuto ~': [],
    'kuma gurashi': [],
    'la ykhr fy alshrk': [],
    "lee seop's love": [],
    'lee seops love': [],
    'legend of sho': ['Historical', 'Action', 'Adventure', 'Fantasy'],
    'legend of star general': ['Sci-Fi', 'Action', 'Mecha', 'Drama'],
    'legend of the northern blade': ['Action', 'Adventure', 'Fantasy'],
    'legend of the reincarnated demon god': ['Action', 'Adventure', 'Wuxia'],
    'lemon tree grove': [],
    'let me play in peace': [],
    'level drain': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'level up with skills': [],
    'leveling up my lifes luck': [],
    'leveling up with gods': ['Action', 'Adventure', 'Fantasy'],
    'leveling up, by only eating!': ['Action', 'Comedy', 'Adventure', 'Fantasy'],
    'leviathan table': [],
    'life of a magic academy mage': [],
    'life of a war emperor after retirement': ['Action', 'Comedy', 'Fantasy'],
    'life or death for an unrequited love': [],
    'light of the dawn remake': ['Action', 'Fantasy'],
    'lightning degree': [],
    'like a chilling flame': ['Action', 'Wuxia', 'Drama', 'Fantasy'],
    'lingering pain': [],
    'live with me': ['Adventure', 'Slice of Life'],
    'living with an aberrant lifeform in my body': [],
    'logging 10 000 years into the future': [],
    'logging 10.000 years into the future': [],
    'looking for a top-tier fighting coach': [],
    'looking for the strongest': [],
    'looking for the villainess’s contract husband': ['Romance', 'Isekai', 'Fantasy'],
    'lookism': ['Action', 'Comedy', 'Crime', 'Drama'],
    "lord preston's secret tutor": ['Romance', 'Drama', 'Fantasy'],
    'lord preston’s secret tutor': ['Romance', 'Drama', 'Fantasy'],
    'loyal heart roaming the skies': [],
    'lsk': [],
    "lu bu's life simulator": ['Action', 'Adventure'],
    'lu bus life simulator': [],
    'magic academy’s genius blinker': [],
    'magic level 99990000 all-attribute great sage': [],
    'manager kim': [],
    'margraves worthless son': [],
    "marked as the tyrant's daughter in law": ['Romance', 'Isekai', 'Drama', 'Fantasy'],
    'marquis maron': [],
    'marriage defense scandal': [],
    'marriage of convenience 2: an unforgettable song': [],
    'martial arts alone': ['Action', 'Adventure', 'Drama'],
    'martial arts of demonic humans': [],
    'martial peak': ['Action', 'Adventure', 'Wuxia', 'Fantasy'],
    'max level player': [],
    'maxed out leveling': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy', 'Tragedy'],
    'maxed strength necromancer': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'me and my brother': [],
    'medical martial arts': [],
    'memoir of the king of war': ['Historical', 'Action', 'Adventure', 'Fantasy', 'Tragedy'],
    'mercenary enrollment': [],
    'metropolitan reverence': ['Action', 'Comedy', 'Adventure'],
    'mharaty alkamn la tkhr': [],
    'miracle app store\u200f': ['Sci-Fi', 'Action', 'Adventure', 'Fantasy', 'Slice of Life', 'Tragedy'],
    'monopolizing fortunes': [],
    'monster pet evolution': [],
    'mookhyang - dark lady': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'moon-shadow sword emperor': ['Action', 'Drama', 'Fantasy'],
    'mortal cultivation: biography': [],
    'mortals cultivation journey to immortality': [],
    'mount hua sects genius phantom swordsman': [],
    'mountain of corpses and sea of blood': ['Thriller', 'Action', 'Superhero', 'Adventure', 'Fantasy'],
    'mr devourer please act like a final boss': [],
    'murim login': [],
    'murim psychopath': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'mushoku tensei - isekai ittara honki dasu': [],
    'my basic attacks summon the undead i the dark ranger am the true calamity': [],
    'my clone is the space bug king': ['Sci-Fi', 'Action', 'Mecha', 'Adventure', 'Drama', 'Fantasy'],
    'my dad is the strongest under heaven': [],
    'my daddy hides his power': ['Romance', 'Comedy', 'Isekai', 'Fantasy'],
    'my daughter is the final boss': ['Action', 'Romance', 'Adventure', 'Fantasy'],
    'my dream is to get my own house': [],
    'my guild is full of demons': ['Action', 'Adventure', 'Fantasy', 'Mystery'],
    'my healing skill can copy anything so i conquered the abyss': [],
    'my house is a magic power spot': ['Action', 'Romance', 'Comedy', 'Adventure', 'Isekai', 'Fantasy', 'Slice of Life'],
    'my husband possessed the protagonist': [],
    'my inventory is abnormal': ['Action', 'Adventure', 'Fantasy'],
    'my life as a loser': ['Action', 'Comedy', 'Drama'],
    'my pirate prince': [],
    'my plug-in spirit ring': [],
    'my school life pretending to be a worthless person': ['Thriller', 'Action', 'Psychological', 'Adventure', 'Drama', 'Fantasy'],
    'my simulated path to immortality': ['Action', 'Drama', 'Fantasy'],
    'my sister who was my enemy loves me': [],
    'my sister, who was my enemy, loves me': [],
    'my slain dragon bride': ['Action', 'Comedy', 'Fantasy'],
    'my wife is actually the empress': ['Action', 'Romance', 'Comedy', 'Isekai'],
    'my younger sister was a genius': ['Drama', 'Slice of Life'],
    'myst might mayhem': [],
    'nano machine': ['Sci-Fi', 'Action', 'Adventure', 'Wuxia', 'Fantasy'],
    'nation class dungeon architect': [],
    'nation-class dungeon architect': [],
    'national level big shots flock to my farm': [],
    'necromancer academys genius summoner': ['Action', 'Romance', 'Adventure', 'Fantasy'],
    "never mind the heir i'll focus on healing": [],
    'never mind the heir, i’ll focus on healing': [],
    'ngoxhy': [],
    'night at the crossroads': [],
    'nightmare realm summoner': [],
    'noble lady reformation guide': [],
    'now it’s your turn to regret': [],
    'nuclear explosion swordsmanship: one slash, one kill': [],
    'oh! my maid': ['Historical', 'Romance', 'Fantasy'],
    'omniscient reader’s viewpoint': ['Action', 'Adventure', 'Fantasy'],
    'on a perfect revenge': [],
    'on getting the power of god': [],
    'one day, i became a hatchling.': ['Romance', 'Comedy', 'Isekai', 'Fantasy', 'Slice of Life'],
    'one piece': ['Sci-Fi', 'Action', 'Comedy', 'Adventure', 'Drama', 'Fantasy'],
    'one-of-a-kind irregular': [],
    'operation heart pounding': [],
    'operation heart-pounding': [],
    'outcast necromancer': [],
    'outlaws': [],
    'overpowered sword': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'oversummoned, overpowered, and over it!': ['Action', 'Comedy', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'past life regressor [remake]': [],
    'past life returner 2022': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'past lives of the thunder god': [],
    'path of the shaman': [],
    'pavane for the dead hunter': [],
    'pick me up : infinite gacha': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'plastic sisters': [],
    'player': ['Action', 'Comedy', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'player who returned 10,000 years later': [],
    'please give me the pacifier': ['Historical', 'Romance', 'Fantasy'],
    'pmu': [],
    'pobstoez': [],
    'poison dragon: the legend of an asura': ['Action', 'Adventure', 'Drama', 'Fantasy', 'Tragedy'],
    'pokémon adventures': ['Thriller', 'Sci-Fi', 'Action', 'Comedy', 'Sports', 'Adventure', 'Drama', 'Fantasy', 'Slice of Life', 'Tragedy'],
    'post-apocalyptic dispatch company': ['Sci-Fi', 'Action', 'Adventure', 'Drama'],
    'pride of the blade': ['Historical', 'Action', 'Drama', 'Fantasy'],
    'raising villains the right way': [],
    'ranker who lives a second time': [],
    'rcd': [],
    'reaper of the drifting moon': ['Action', 'Adventure', 'Drama', 'Fantasy', 'Mystery'],
    'rebirth monarch of the dead': [],
    'rebirth of the divine demon': [],
    'rebirth: monarch of the dead': [],
    'rebirth: my vengeance through the mirror': [],
    'reborn as the heavenly demon': ['Action', 'Wuxia'],
    'reckless captain of the guard in a medieval fantasy': [],
    'record of lodoss war: the necromancer queen': [],
    'records of the swordsman scholar': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'red shirt': ['Action', 'Drama'],
    'reformation of the deadbeat noble': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'regressed genius creates mythic items': [],
    'regressing as the reincarnated bastard of the sword clan': [],
    'regressing with the king’s power': [],
    'regression of the yong clan heir': ['Action', 'Wuxia', 'Drama', 'Fantasy'],
    'reincarnated as a genius prodigy of a prestigious family': [],
    'reincarnated as a son of an aristocrat': ['Action', 'Isekai', 'Drama', 'Fantasy'],
    'reincarnated as the weakest warrior with the power to choose any reward': [],
    'reincarnated as the youngest son of a demon swordsman family': [],
    'reincarnated escort warrior': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'reincarnation of the fist king': ['Action', 'Adventure', 'Fantasy'],
    'reincarnation of the heavenly demon': [],
    'reincarnation path of the underworld king': [],
    'reincarnator': ['Action', 'Isekai', 'Fantasy'],
    'reincarnators stream': [],
    'reincarnator’s stream': [],
    'reset life of a game addict': ['Drama', 'Fantasy', 'Slice of Life'],
    'return of the 8th class magician': ['Action', 'Adventure', 'Fantasy'],
    'return of the apocalypse class death knight': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'return of the apocalypse-class death knight': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'return of the bachelor': ['Historical', 'Action', 'Fantasy', 'Slice of Life'],
    'return of the disaster-class hero': ['Action', 'Comedy', 'Adventure', 'Fantasy'],
    'return of the first generation': [],
    'return of the first generation the strongest in history reincarnates as his descendant 1000 years later': [],
    'return of the frozen player': ['Action', 'Adventure', 'Fantasy'],
    'return of the hated black mage': [],
    'return of the legendary spear knight': [],
    'return of the mount hua sect': [],
    'return of the reaper assassin': [],
    'return of the runebound professor': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'revenge of the bloom flower': [],
    'revenge of the iron blooded sword hound': [],
    'revenge of the iron-blooded sword hound': [],
    'reverse villain': ['Action', 'Comedy', 'Superhero', 'Wuxia', 'Isekai'],
    'riding on the edge of annihilation': ['Action', 'Fantasy', 'Mystery'],
    'rise from the rubble': ['Sci-Fi', 'Action', 'Adventure', 'Fantasy'],
    'rise of the demon king': [],
    'rise of the devourer king': ['Action', 'Isekai'],
    'rise of the god slaying master': [],
    'rise of the limitless necromancer': [],
    'rise of the mushroom king': [],
    'road to mastery': [],
    'rogue of doom': ['Action', 'Comedy', 'Adventure', 'Wuxia', 'Fantasy'],
    'rookie but one in a million actor': [],
    'rookie employee kim cheolsu': ['Drama', 'Fantasy'],
    'rp': [],
    'rust': ['Thriller', 'Action'],
    'ryūgari no nato –dragon hunt tribe–': [],
    's-class hunter heals with monsters': [],
    'sandmancer of the scorched desert': [],
    'sangeki': ['Action', 'Drama'],
    'saved by the powerless little lady': [],
    'saving the villain who was abandoned by the female lead': [],
    'secret family': ['Action', 'Adventure', 'Drama'],
    'secretly more powerful than the hero': ['Action', 'Comedy', 'Adventure', 'Drama', 'Fantasy'],
    'serpent ancestor': [],
    'shadow of the reborn rogues dominion': [],
    'shadow slave': ['Thriller', 'Action', 'Romance', 'Adventure', 'Drama', 'Fantasy', 'Mystery', 'Tragedy'],
    'shangri-la frontier': ['Sci-Fi', 'Action', 'Adventure', 'Drama', 'Fantasy'],
    'she was sent for him': [],
    "she wasn't my daughter": [],
    'she wasnt my daughter': [],
    'shingeki no kyojin': ["Boys' Love"],
    'sicario': [],
    "since i'm a time limited princess who has no tomorrow": [],
    'since i’m a time-limited princess who has no tomorrow': [],
    'single dad in another realm': ['Action', 'Adventure', 'Fantasy', 'Slice of Life'],
    'sir': [],
    'skeleton soldier couldnt protect the dungeon': ['Action', 'Adventure', 'Fantasy'],
    'skeleton soldier couldn’t protect the dungeon': ['Action', 'Adventure', 'Fantasy'],
    'skeleton warrior': ['Action', 'Adventure', 'Fantasy'],
    'sleeping ranker': [],
    'solmi solfa, my song': [],
    'solo bug player': [],
    'solo farming in the tower': [],
    'solo leveling': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'solo leveling: ragnarok': ['Action', 'Adventure', 'Fantasy'],
    'solo login': ['Action', 'Adventure', 'Fantasy'],
    'solo max-level newbie': [],
    'sorry, my skills are automatically maxed out!': [],
    'special contract marriage': [],
    'spend more earn more': [],
    'spend more, earn more': [],
    'sss grade saint knight': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    "sss-class assassin's return": [],
    'standard of reincarnation': [],
    'star in the daytime': ['Romance', 'Drama'],
    'star instructor, master baek': [],
    'star martial god technique': [],
    'star-embracing swordmaster': [],
    'start by signing in and obtaining the ancient divine body': ['Action', 'Comedy', 'Wuxia', 'Isekai', 'Drama', 'Fantasy'],
    'starting as the black dragon boss i am invincible': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'starting with 13 hidden traits': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'steel-eating player': ['Action', 'Drama', 'Fantasy'],
    'street restaurant of a returned hero': [],
    'strongest abandoned son (new)': ['Action', 'Romance', 'Adventure', 'Fantasy'],
    'strongest fighter': [],
    'strongest level 1': [],
    'study group': ['Action', 'Comedy', 'Drama'],
    'super evolution': [],
    'super god gene': ['Sci-Fi', 'Action', 'Comedy', 'Adventure'],
    'super god pet beast shop': [],
    'super nova': [],
    'superhuman battlefield': ['Action', 'Sports', 'Fantasy'],
    'superstar from age 0': ['Comedy', 'Adventure', 'Drama', 'Fantasy'],
    'supreme curse master': [],
    'supreme demon of hyungsan': [],
    'supreme fair trade authority': [],
    'supreme red packet emperor': [],
    'supreme zerg lord': [],
    'survivalism': ['Sci-Fi', 'Action', 'Adventure', 'Isekai', 'Horror', 'Fantasy'],
    'surviving as a genius on borrowed time': [],
    'surviving in a school bully webtoon': [],
    'surviving in an rpg maker horror game': [],
    'surviving in another world': [],
    'surviving the apocalypse': ['Action', 'Drama', 'Fantasy'],
    'surviving the game as a barbarian': ['Action', 'Romance', 'Adventure', 'Isekai', 'Fantasy'],
    'survivor story of a sword king in a fantasy world': [],
    'swallow the whole world': ['Action', 'Drama'],
    'sword dance online': ['Action', 'Romance', 'Comedy', 'Adventure', 'Fantasy'],
    'sword god high school the talentless underachiever becomes the strongest': [],
    'sword god high school: the talentless underachiever becomes the strongest': [],
    "sword god's livestream": [],
    "sword sheath's child": [],
    "swordmaster's youngest son": [],
    'swordsman of sichuan tang family': [],
    'tale of a scribe who retires to the countryside': [],
    'talent-swallowing magician': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'tales of demons and gods': ['Historical', 'Action', 'Comedy', 'Adventure', 'Drama', 'Fantasy'],
    'taming master': ['Action', 'Adventure', 'Fantasy'],
    'tengoku daimakyou': ['Romance'],
    'tenkaichi: nihon saikyou bugeisha ketteisen': [],
    'territory defense with tamed monsters': [],
    'test manga 3': [],
    'tgmra4000y': [],
    'the 100th regression of the max-level player': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'the 31st piece turns the tables': [],
    'the abyssal seed': ['Action', 'Drama', 'Fantasy'],
    'the academy’s sashimi sword master': ['Action', 'Isekai', 'Drama', 'Fantasy', 'Mystery'],
    'the age of arrogance': ['Romance', 'Fantasy'],
    'the apocalypse has come': [],
    'the apocalypse needs a pro': [],
    'the archduke’s flower is in jeopardy': [],
    "the archmage's restaurant": ['Action', 'Romance', 'Comedy', 'Adventure', 'Isekai', 'Fantasy', 'Slice of Life'],
    'the art of leaving work on time': [],
    'the avenging assassin doll': [],
    'the baby raising a devil': ['Romance', 'Drama', 'Fantasy'],
    'the back-alley mage’s return': [],
    'the baddest villainess is back': [],
    'the bat knight: dan': [],
    'the blood princess and the knight': ['Action', 'Psychological', 'Adventure', 'Drama', 'Fantasy', 'Tragedy'],
    'the book eating magician': ['Action', 'Adventure', 'Drama', 'Fantasy'],
    'the butcher blade that pierces all realms': [],
    'the calamity prince wants the fake princess': [],
    'the care alliance': [],
    'the chairman of pharmaceutical company is a poison king': [],
    'the chairman who just wants to slack off': [],
    'the cleaners agent': ['Thriller', 'Action', 'Crime', 'Adventure', 'Drama'],
    'the constellations are my disciples': ['Action', 'Drama', 'Fantasy'],
    'the corruption-immune swordsman’s calamity sword': [],
    "the count's secret maid": ['Romance', 'Drama'],
    "the count's youngest son is a player": ['Isekai', 'Fantasy'],
    'the counts youngest son is a player': ['Isekai', 'Fantasy'],
    'the crown prince that sells medicine': [],
    'the dark mage’s return to enlistment': [],
    'the dark swordsman returns': [],
    'the delivery man from murim': ['Action', 'Isekai', 'Fantasy'],
    'the demon king overrun by heroes': [],
    'the demon king who lost his job': [],
    'the demonic cult instructor returns': [],
    'the demonic cult leader is too reluctant': [],
    'the descent of the demonic master': ['Action', 'Adventure', 'Wuxia'],
    'the diary of loving a forgetful sweet wife': [],
    'the divine ring descends the strongest otherworld': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'the divine ring descends: the strongest otherworld': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'the dragon of kunlun': [],
    'the duchess with an empty soul': ['Romance', 'Drama', 'Fantasy'],
    'the duke needs home education': [],
    'the dungeon painter': [],
    'the dutiful kid who saved the villainous family': [],
    'the empire’s villainess': [],
    'the eternal calamity': [],
    'the eternal supreme': [],
    'the extras academy survival guide': ['Action', 'Romance', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the extra’s academy survival guide': ['Action', 'Romance', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the father and the daughter': [],
    'the final boss became a player': [],
    'the final boss wants to die': [],
    'the forgotten field': ['Historical', 'Romance', 'Drama', 'Fantasy'],
    'the forgotten fields': [],
    'the fox-eyed villain of the demon academy': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the genius assassins second life at the academy': [],
    'the genius midfielders passes are special': ['Action', 'Sports'],
    'the genius wants to be ordinary': [],
    'the genius who reads the world': [],
    'the glutton': ['Thriller', 'Action', 'Adventure'],
    'the god of war is leveling up': ['Action', 'Drama', 'Fantasy'],
    'the goddess of fortune': [],
    'the golden haired elementalist': [],
    "the grand duke's new daughter in law is a little fierce": [],
    'the grand duke’s new daughter-in-law is a little fierce': [],
    'the great mage returns after 4000 year s': ['Action', 'Adventure', 'Fantasy'],
    'the great mage returns after 4000 years': ['Action', 'Adventure', 'Fantasy'],
    'the heavenly demons apocalypse': [],
    'the hero starts over at the academy': [],
    "the heroine's sister-in-law in a childcare story": ['Romance', 'Drama', 'Fantasy'],
    'the holy power of modern medicine': ['Action', 'Adventure', 'Isekai', 'Drama', 'Medical', 'Fantasy'],
    'the illegitimate who devours weapons': [],
    'the imperial maiden': ['Romance', 'Drama', 'Fantasy'],
    'the indomitable martial king': ['Action', 'Drama', 'Fantasy'],
    'the investor who sees the future': ['Action', 'Adventure', 'Fantasy'],
    'the iron and ice journey': ['Sci-Fi', 'Drama'],
    'the iron-blooded necromancer has returned': ['Action', 'Drama', 'Fantasy'],
    'the jinxs strategy for domination': [],
    'the joseon prince went to america and didnt return': ['Historical', 'Adventure', 'Drama', 'Fantasy'],
    'the killer lawyer': [],
    'the king of snow': [],
    'the king of the special forces': ['Action', 'Comedy', 'Fantasy'],
    'the lady is a stalker': ['Romance', 'Isekai', 'Fantasy'],
    'the last adventurer': ['Action', 'Adventure', 'Fantasy'],
    'the last golden child': ['Action', 'Adventure', 'Fantasy'],
    'the last summoner': ['Action', 'Mecha', 'Adventure', 'Drama', 'Fantasy'],
    'the legend of the twin dragons': ['Historical', 'Romance', 'Comedy', 'Drama'],
    'the legendary assassin reincarnated as the beloved youngest daughter': ['Action', 'Magical Girls', 'Fantasy'],
    'the legendary hero is an academy honors student': ['Action', 'Adventure', 'Fantasy'],
    'the legendary moonlight sculptor': ['Action', 'Romance', 'Comedy', 'Adventure', 'Drama', 'Fantasy'],
    'the level 9999 underachiever dominates in a woman ruled world': [],
    'the little bear in the black fox mansion': [],
    'the little brother is the academy’s hotshot': [],
    'the lord of money': [],
    'the lord who levels up by absorbing powers': [],
    'the lord who levels up by devouring': [],
    'the lords coins arent decreasing': ['Action', 'Adventure', 'Fantasy'],
    'the low ranking civil servant wants to achieve success': [],
    'the mad dog of the duke’s estate': ['Action', 'Adventure', 'Fantasy'],
    "the magic tower's problem child": [],
    'the maid with a child': [],
    'the main characters that only i know': ['Action', 'Adventure', 'Fantasy'],
    'the main heroines are trying to kill me': [],
    'the male lead is obsessed with my health': [],
    'the mansion awaits spring': [],
    'the mansion awaits spring1': [],
    'the martial genius who remembers everything': [],
    'the max leveled hero will return': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'the memoir of a certain evil wizard': [],
    'the misfit of the martial world': [],
    'the moon witch and the sun king: my salvation': ['Romance', 'Comedy', 'Isekai', 'Fantasy'],
    'the mysterious world’s greatest martial artist little prince': [],
    'the mythical realm': ['Action', 'Romance', 'Comedy', 'Adventure', 'Fantasy'],
    "the necromancer family's young heir": ['Action', 'Drama', 'Fantasy'],
    'the ninth-rank sword master': ['Action', 'Adventure', 'Fantasy'],
    'the nis rookie': [],
    "the novel's extra": ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the novels extra 2': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the novel’s extra': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    "the novice's frontline": [],
    'the obsessive maniacs is trying to confine': [],
    'the old man swears vengeance against his demonic wife': [],
    'the oracle of the villainous baby': [],
    'the oracle of the villainous baby1': [],
    'the over invested unrequited crush club': [],
    'the over-invested unrequited crush club': [],
    'the path toward heaven': [],
    'the peaceful life of a maid who hides her power and enjoys it': [],
    'the peerless concubine': [],
    'the player hides his past': ['Action', 'Comedy', 'Drama', 'Fantasy'],
    'the player of the fallen family': [],
    'the politician who can see the future': [],
    'the priest of corruption': [],
    'the princess wants to die comfortably': [],
    'the princess who returned by dying became the tyrants personal chef': [],
    'the princess who returned by dying became the tyrant’s personal chef': [],
    'the problematic children of the magic tower': [],
    'the ravages of time (rot)': ['Historical', 'Action', 'Psychological', 'Romance', 'Adventure', 'Drama', 'Mystery'],
    'the rebel of the tyrant noble family': [],
    'the red king': ['Adventure', 'Fantasy', 'Mystery'],
    "the regressed mercenary's machinations": [],
    'the regressed son of a duke is an assassin': ['Action', 'Drama', 'Fantasy'],
    'the reincarnated assassin is a genius swordsman': ['Adventure', 'Fantasy'],
    'the reincarnation magician of the inferior eyes': [],
    'the return of apocalypses tyrant': [],
    'the return of senior disciple lee hoo': [],
    'the return of the crazy demon s': [],
    'the return of the musical genius': [],
    'the return of the s-rank holy weapon user from the duke’s family': ['Action', 'Adventure', 'Fantasy'],
    'the return of the unrivaled genius ranker': [],
    'the returnees hidden strategy stream': [],
    'the returners road to retirement': ['Action', 'Comedy', 'Adventure', 'Fantasy'],
    'the reversal of my life as a side character': [],
    'the road of karma': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the ruined world was mistaken for a game': [],
    'the ruler of darkness': [],
    'the saint levels up through necromancy': [],
    'the scorched desert’s sand mage': [],
    'the second eunuch regains his manhood': [],
    'the serpent of paradise': ['Romance', 'Drama', 'Fantasy'],
    'the seventh prince wants to bail': [],
    'the shepherd wizard': ['Action', 'Adventure', 'Fantasy'],
    'the sorcerer king of destruction and the golem of the barbarian queen': ['Action', 'Romance', 'Comedy', 'Adventure', 'Isekai', 'Fantasy'],
    'the steel emperor': ['Action', 'Adventure', 'Isekai'],
    'the story of a low-rank soldier becoming a monarch': [],
    'the strongest reincarnated as a mediocre heir of a prestigious family': [],
    'the strongest romantic': [],
    'the strongest swordsman rising from a bottom tier job': [],
    'the strongest swordsman rising from a bottom-tier job': [],
    'the substitute hero': [],
    'the summer swallowed by darkness': ['Romance', 'Drama'],
    'the superhuman era': [],
    'the support ate it all': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    'the supreme demonic sword': ['Action', 'Adventure', 'Tragedy'],
    'the supreme poison demon becomes a pharma chairman': [],
    'the sword emperor who surpasses his previous life': [],
    'the sword saint reincarnated into a noble mage family': [],
    'the tale of cultivation and demon extermination': [],
    'the tang clan chronicles': [],
    'the terminally ill young master of the baek clan': [],
    'the theory of useless magic': [],
    'the timid frontier heiress never gives up her revenge': [],
    'the top player returns': [],
    "the top ranker's aspiring writer life manual": [],
    'the tutorial is too hard': ['Action', 'Psychological', 'Adventure', 'Isekai', 'Fantasy'],
    'the tyrant girl neros rebellion': [],
    'the ultimate prodigy': [],
    'the ultimate shut-in': ['Drama', 'Fantasy'],
    'the undefeatable swordsman': ['Action', 'Adventure', 'Wuxia'],
    'the underworld transcendent is unrivaled at the school': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    "the underworld's broker": [],
    'the veteran healer is too strong': [],
    'the veteran swordmasters stream': ['Action', 'Fantasy'],
    'the villain wants to live': ['Action', 'Psychological', 'Comedy', 'Isekai', 'Drama', 'Fantasy', 'Tragedy'],
    'the villainess captured the male lead': [],
    'the villainess sister hides her wealth': ['Romance', 'Isekai', 'Drama', 'Fantasy'],
    'the villainous sister hides her wealth': ['Romance', 'Isekai', 'Drama', 'Fantasy'],
    'the villains match is too perfect': ['Romance', 'Isekai', 'Fantasy'],
    'the villainss favourite is me': [],
    'the wandering knights survival manual': [],
    'the wandering knight’s survival manual': [],
    'the weakest occupation "blacksmith," but it\'s actually the strongest': [],
    "the well-mannered husband's motive for marriage is suspicious": [],
    'the world after the fall': ['Action', 'Adventure', 'Isekai', 'Drama', 'Fantasy'],
    "the world's best engineer": [],
    'the worlds best martial arts instructor': ['Action', 'Drama', 'Fantasy'],
    'the world’s best martial arts instructor': ['Action', 'Drama', 'Fantasy'],
    'the youngest daughter of the great magician of a famous swordsmanship family': [],
    'the youngest filming a childcare reality show is adorable': [],
    'the youngest son of a conglomerate': [],
    'the youngest son of the eunhae merchant group': [],
    'the zenith': ['Sci-Fi', 'Action', 'Adventure', 'Fantasy'],
    'there is no place for fakes': [],
    'theres no such thing as a bad hero in the world': [],
    'there’s no such thing as a bad hero in the world': [],
    'third rate martial family becomes the best under heaven': [],
    'this assassin is upright': [],
    'this is an obvious fraudulent marriage': ['Romance', 'Comedy', 'Adventure', 'Isekai', 'Fantasy', 'Slice of Life'],
    'this is the law': ['Action', 'Crime', 'Drama', 'Fantasy'],
    'this killer is a son in law': [],
    'this witch of mine': [],
    'tigers': [],
    'to hell with being heir im going to heal': ['Action', 'Adventure', 'Fantasy'],
    'to hell with the status window': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'to my sweetheart': ['Romance', 'Comedy'],
    'to not die': ['Action', 'Crime', 'Adventure', 'Tragedy'],
    'transcendence due to a system error': [],
    'trapped in a crazy world as an extra': ['Action', 'Isekai', 'Drama', 'Fantasy'],
    'trash of the count’s family': ['Romance', 'Isekai', 'Fantasy'],
    'true martial world': ['Action', 'Isekai'],
    'turns out im a third generation chaebol': [],
    'umineko episode 1 legend of the golden witch': ['Psychological', 'Drama', 'Horror', 'Fantasy', 'Mystery'],
    'umineko no naku koro ni chiru episode 7 requiem of the golden witch': [],
    'umineko no naku koro ni chiru episode 8 twilight of the golden witch': [],
    'underworld monarch i am the abyss': [],
    'underworld restaurant': [],
    'unrivaled spear demon': [],
    'urban dragon war': [],
    'using my cooking skills in a murim world': ['Historical', 'Action', 'Comedy', 'Adventure', 'Slice of Life'],
    'vagabond': ['Historical', 'Action', 'Psychological', 'Romance', 'Comedy', 'Adventure', 'Drama', 'Tragedy'],
    'vanitas no carte': [],
    'versatile mage': [],
    "villain family's strongest butler": [],
    'villain is here': ['Action', 'Adventure', 'Wuxia', 'Isekai', 'Fantasy'],
    "violet's last word": [],
    'violet’s last word': [],
    'vote for your knight!': [],
    'wae': [],
    'warrior grandpa and supreme granddaughter': ['Action', 'Comedy', 'Drama', 'Fantasy', 'Tragedy'],
    'warrior high school – dungeon raid department': ['Action', 'Fantasy'],
    "wasn't i the female lead of a regret novel?": [],
    'watashi no shiawase na kekkon': [],
    'wbe': [],
    'weryre': [],
    'wfjsra': [],
    'what happens when a dying secret agent moves to the countryside': [],
    'when a genius office worker goes too far': ['Drama', 'Slice of Life'],
    'why would a villainess have virtue?': [],
    'wild ranker': ['Action', 'Adventure', 'Fantasy'],
    'wild west murim': ['Action', 'Adventure', 'Isekai'],
    'wind breaker': ['Action', 'Comedy', 'Slice of Life'],
    'winter carnival': ['Psychological', 'Romance', 'Drama', 'Mystery'],
    'wish': ['Thriller', 'Psychological', 'Drama', 'Horror'],
    'wonderland': ['Comedy', 'Adventure', 'Drama', 'Horror', 'Mystery'],
    'world saving is a skill': ['Action', 'Isekai', 'Fantasy'],
    "world's strongest survivor": ['Sci-Fi', 'Action', 'Drama', 'Fantasy'],
    'world’s greatest senior disciple': [],
    'world’s ruler': [],
    'worn and torn newbie': ['Action', 'Adventure', 'Fantasy'],
    'wrecker driver': ['Action', 'Psychological', 'Drama', 'Tragedy'],
    'xian ni': [],
    'xqnzna': [],
    'y5yadw8hjmcpur': [],
    'young lady is a royal chef': ['Romance', 'Isekai', 'Drama', 'Fantasy'],
    'youngest scion of the mages': ['Action', 'Adventure', 'Isekai', 'Fantasy'],
    'zero level hero': [],
    'zombie apocalypse 82 08': ['Action', 'Crime', 'Adventure', 'Drama'],
    'مانغا': [],
    'معجزة ونبوءة': [],
    '\u200feverlasting longing': [],
    "\u200fi'm a sickly mother, but i'll raise my villainous son!": ['Romance', 'Isekai', 'Fantasy'],
    '\u200fi’m a former office worker reborn as the villainess of the apocalypse': [],
    '\u200fnearby muscle girl': [],
}
